// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway.proto

package com.xml2023.flights;

public final class Gateway {
  private Gateway() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TokenValidanRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xml2023.flights.TokenValidanRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string apiToken = 1;</code>
     */
    java.lang.String getApiToken();
    /**
     * <code>string apiToken = 1;</code>
     */
    com.google.protobuf.ByteString
        getApiTokenBytes();
  }
  /**
   * Protobuf type {@code com.xml2023.flights.TokenValidanRequest}
   */
  public  static final class TokenValidanRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xml2023.flights.TokenValidanRequest)
      TokenValidanRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TokenValidanRequest.newBuilder() to construct.
    private TokenValidanRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TokenValidanRequest() {
      apiToken_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TokenValidanRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              apiToken_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xml2023.flights.Gateway.internal_static_com_xml2023_flights_TokenValidanRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xml2023.flights.Gateway.internal_static_com_xml2023_flights_TokenValidanRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xml2023.flights.Gateway.TokenValidanRequest.class, com.xml2023.flights.Gateway.TokenValidanRequest.Builder.class);
    }

    public static final int APITOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object apiToken_;
    /**
     * <code>string apiToken = 1;</code>
     */
    public java.lang.String getApiToken() {
      java.lang.Object ref = apiToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apiToken_ = s;
        return s;
      }
    }
    /**
     * <code>string apiToken = 1;</code>
     */
    public com.google.protobuf.ByteString
        getApiTokenBytes() {
      java.lang.Object ref = apiToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apiToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getApiTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, apiToken_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getApiTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, apiToken_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xml2023.flights.Gateway.TokenValidanRequest)) {
        return super.equals(obj);
      }
      com.xml2023.flights.Gateway.TokenValidanRequest other = (com.xml2023.flights.Gateway.TokenValidanRequest) obj;

      boolean result = true;
      result = result && getApiToken()
          .equals(other.getApiToken());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APITOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getApiToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xml2023.flights.Gateway.TokenValidanRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xml2023.flights.Gateway.TokenValidanRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xml2023.flights.Gateway.TokenValidanRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xml2023.flights.Gateway.TokenValidanRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xml2023.flights.Gateway.TokenValidanRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xml2023.flights.Gateway.TokenValidanRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xml2023.flights.Gateway.TokenValidanRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xml2023.flights.Gateway.TokenValidanRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xml2023.flights.Gateway.TokenValidanRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xml2023.flights.Gateway.TokenValidanRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xml2023.flights.Gateway.TokenValidanRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xml2023.flights.Gateway.TokenValidanRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xml2023.flights.Gateway.TokenValidanRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xml2023.flights.TokenValidanRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xml2023.flights.TokenValidanRequest)
        com.xml2023.flights.Gateway.TokenValidanRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xml2023.flights.Gateway.internal_static_com_xml2023_flights_TokenValidanRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xml2023.flights.Gateway.internal_static_com_xml2023_flights_TokenValidanRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xml2023.flights.Gateway.TokenValidanRequest.class, com.xml2023.flights.Gateway.TokenValidanRequest.Builder.class);
      }

      // Construct using com.xml2023.flights.Gateway.TokenValidanRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        apiToken_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xml2023.flights.Gateway.internal_static_com_xml2023_flights_TokenValidanRequest_descriptor;
      }

      @java.lang.Override
      public com.xml2023.flights.Gateway.TokenValidanRequest getDefaultInstanceForType() {
        return com.xml2023.flights.Gateway.TokenValidanRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.xml2023.flights.Gateway.TokenValidanRequest build() {
        com.xml2023.flights.Gateway.TokenValidanRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xml2023.flights.Gateway.TokenValidanRequest buildPartial() {
        com.xml2023.flights.Gateway.TokenValidanRequest result = new com.xml2023.flights.Gateway.TokenValidanRequest(this);
        result.apiToken_ = apiToken_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xml2023.flights.Gateway.TokenValidanRequest) {
          return mergeFrom((com.xml2023.flights.Gateway.TokenValidanRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xml2023.flights.Gateway.TokenValidanRequest other) {
        if (other == com.xml2023.flights.Gateway.TokenValidanRequest.getDefaultInstance()) return this;
        if (!other.getApiToken().isEmpty()) {
          apiToken_ = other.apiToken_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xml2023.flights.Gateway.TokenValidanRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xml2023.flights.Gateway.TokenValidanRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object apiToken_ = "";
      /**
       * <code>string apiToken = 1;</code>
       */
      public java.lang.String getApiToken() {
        java.lang.Object ref = apiToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          apiToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string apiToken = 1;</code>
       */
      public com.google.protobuf.ByteString
          getApiTokenBytes() {
        java.lang.Object ref = apiToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          apiToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string apiToken = 1;</code>
       */
      public Builder setApiToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        apiToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string apiToken = 1;</code>
       */
      public Builder clearApiToken() {
        
        apiToken_ = getDefaultInstance().getApiToken();
        onChanged();
        return this;
      }
      /**
       * <code>string apiToken = 1;</code>
       */
      public Builder setApiTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        apiToken_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xml2023.flights.TokenValidanRequest)
    }

    // @@protoc_insertion_point(class_scope:com.xml2023.flights.TokenValidanRequest)
    private static final com.xml2023.flights.Gateway.TokenValidanRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xml2023.flights.Gateway.TokenValidanRequest();
    }

    public static com.xml2023.flights.Gateway.TokenValidanRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TokenValidanRequest>
        PARSER = new com.google.protobuf.AbstractParser<TokenValidanRequest>() {
      @java.lang.Override
      public TokenValidanRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TokenValidanRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TokenValidanRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TokenValidanRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xml2023.flights.Gateway.TokenValidanRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TokenValidanResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xml2023.flights.TokenValidanResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool result = 1;</code>
     */
    boolean getResult();

    /**
     * <code>string tekst = 2;</code>
     */
    java.lang.String getTekst();
    /**
     * <code>string tekst = 2;</code>
     */
    com.google.protobuf.ByteString
        getTekstBytes();
  }
  /**
   * Protobuf type {@code com.xml2023.flights.TokenValidanResponse}
   */
  public  static final class TokenValidanResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xml2023.flights.TokenValidanResponse)
      TokenValidanResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TokenValidanResponse.newBuilder() to construct.
    private TokenValidanResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TokenValidanResponse() {
      result_ = false;
      tekst_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TokenValidanResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              result_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              tekst_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xml2023.flights.Gateway.internal_static_com_xml2023_flights_TokenValidanResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xml2023.flights.Gateway.internal_static_com_xml2023_flights_TokenValidanResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xml2023.flights.Gateway.TokenValidanResponse.class, com.xml2023.flights.Gateway.TokenValidanResponse.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private boolean result_;
    /**
     * <code>bool result = 1;</code>
     */
    public boolean getResult() {
      return result_;
    }

    public static final int TEKST_FIELD_NUMBER = 2;
    private volatile java.lang.Object tekst_;
    /**
     * <code>string tekst = 2;</code>
     */
    public java.lang.String getTekst() {
      java.lang.Object ref = tekst_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tekst_ = s;
        return s;
      }
    }
    /**
     * <code>string tekst = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTekstBytes() {
      java.lang.Object ref = tekst_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tekst_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != false) {
        output.writeBool(1, result_);
      }
      if (!getTekstBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tekst_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, result_);
      }
      if (!getTekstBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tekst_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xml2023.flights.Gateway.TokenValidanResponse)) {
        return super.equals(obj);
      }
      com.xml2023.flights.Gateway.TokenValidanResponse other = (com.xml2023.flights.Gateway.TokenValidanResponse) obj;

      boolean result = true;
      result = result && (getResult()
          == other.getResult());
      result = result && getTekst()
          .equals(other.getTekst());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getResult());
      hash = (37 * hash) + TEKST_FIELD_NUMBER;
      hash = (53 * hash) + getTekst().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xml2023.flights.Gateway.TokenValidanResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xml2023.flights.Gateway.TokenValidanResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xml2023.flights.Gateway.TokenValidanResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xml2023.flights.Gateway.TokenValidanResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xml2023.flights.Gateway.TokenValidanResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xml2023.flights.Gateway.TokenValidanResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xml2023.flights.Gateway.TokenValidanResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xml2023.flights.Gateway.TokenValidanResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xml2023.flights.Gateway.TokenValidanResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xml2023.flights.Gateway.TokenValidanResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xml2023.flights.Gateway.TokenValidanResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xml2023.flights.Gateway.TokenValidanResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xml2023.flights.Gateway.TokenValidanResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xml2023.flights.TokenValidanResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xml2023.flights.TokenValidanResponse)
        com.xml2023.flights.Gateway.TokenValidanResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xml2023.flights.Gateway.internal_static_com_xml2023_flights_TokenValidanResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xml2023.flights.Gateway.internal_static_com_xml2023_flights_TokenValidanResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xml2023.flights.Gateway.TokenValidanResponse.class, com.xml2023.flights.Gateway.TokenValidanResponse.Builder.class);
      }

      // Construct using com.xml2023.flights.Gateway.TokenValidanResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = false;

        tekst_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xml2023.flights.Gateway.internal_static_com_xml2023_flights_TokenValidanResponse_descriptor;
      }

      @java.lang.Override
      public com.xml2023.flights.Gateway.TokenValidanResponse getDefaultInstanceForType() {
        return com.xml2023.flights.Gateway.TokenValidanResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.xml2023.flights.Gateway.TokenValidanResponse build() {
        com.xml2023.flights.Gateway.TokenValidanResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xml2023.flights.Gateway.TokenValidanResponse buildPartial() {
        com.xml2023.flights.Gateway.TokenValidanResponse result = new com.xml2023.flights.Gateway.TokenValidanResponse(this);
        result.result_ = result_;
        result.tekst_ = tekst_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xml2023.flights.Gateway.TokenValidanResponse) {
          return mergeFrom((com.xml2023.flights.Gateway.TokenValidanResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xml2023.flights.Gateway.TokenValidanResponse other) {
        if (other == com.xml2023.flights.Gateway.TokenValidanResponse.getDefaultInstance()) return this;
        if (other.getResult() != false) {
          setResult(other.getResult());
        }
        if (!other.getTekst().isEmpty()) {
          tekst_ = other.tekst_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xml2023.flights.Gateway.TokenValidanResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xml2023.flights.Gateway.TokenValidanResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean result_ ;
      /**
       * <code>bool result = 1;</code>
       */
      public boolean getResult() {
        return result_;
      }
      /**
       * <code>bool result = 1;</code>
       */
      public Builder setResult(boolean value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object tekst_ = "";
      /**
       * <code>string tekst = 2;</code>
       */
      public java.lang.String getTekst() {
        java.lang.Object ref = tekst_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tekst_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tekst = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTekstBytes() {
        java.lang.Object ref = tekst_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tekst_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tekst = 2;</code>
       */
      public Builder setTekst(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tekst_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tekst = 2;</code>
       */
      public Builder clearTekst() {
        
        tekst_ = getDefaultInstance().getTekst();
        onChanged();
        return this;
      }
      /**
       * <code>string tekst = 2;</code>
       */
      public Builder setTekstBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tekst_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xml2023.flights.TokenValidanResponse)
    }

    // @@protoc_insertion_point(class_scope:com.xml2023.flights.TokenValidanResponse)
    private static final com.xml2023.flights.Gateway.TokenValidanResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xml2023.flights.Gateway.TokenValidanResponse();
    }

    public static com.xml2023.flights.Gateway.TokenValidanResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TokenValidanResponse>
        PARSER = new com.google.protobuf.AbstractParser<TokenValidanResponse>() {
      @java.lang.Override
      public TokenValidanResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TokenValidanResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TokenValidanResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TokenValidanResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xml2023.flights.Gateway.TokenValidanResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_flights_TokenValidanRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_flights_TokenValidanRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_flights_TokenValidanResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_flights_TokenValidanResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rgateway.proto\022\023com.xml2023.flights\032\037go" +
      "ogle/protobuf/timestamp.proto\"\'\n\023TokenVa" +
      "lidanRequest\022\020\n\010apiToken\030\001 \001(\t\"5\n\024TokenV" +
      "alidanResponse\022\016\n\006result\030\001 \001(\010\022\r\n\005tekst\030" +
      "\002 \001(\t2o\n\007Flights\022d\n\rvalidateToken\022(.com." +
      "xml2023.flights.TokenValidanRequest\032).co" +
      "m.xml2023.flights.TokenValidanResponseb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_com_xml2023_flights_TokenValidanRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xml2023_flights_TokenValidanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_flights_TokenValidanRequest_descriptor,
        new java.lang.String[] { "ApiToken", });
    internal_static_com_xml2023_flights_TokenValidanResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xml2023_flights_TokenValidanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_flights_TokenValidanResponse_descriptor,
        new java.lang.String[] { "Result", "Tekst", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
