version: '3.9'
services:
  eureka-service:
    image: eureka-service
    build: ./eureka
    restart: unless-stopped
    container_name: eureka
    ports:
      - 8761:8761
  gateway-service:
    image: gateway-service
    ports:
      - "7777:7777"
    environment:
      - EUREKA_SERVER=http://eureka:8761/eureka/
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"

  # reglog-service:
  #   image: reglog-service
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     - EUREKA_SERVER=http://eureka:8761/eureka/
  #     - SPRING_RABBITMQ_HOST=rabbitmq
  #     - SPRING_RABBITMQ_USERNAME=guest
  #     - SPRING_RABBITMQ_PASSWORD=guest
  #     - SPRING_REDIS_HOST=redis
  #     - SPRING_DATA_MONGODB_HOST=mongodb
  #   depends_on:
  #     - eureka-service
  #     - rabbitmq
  #     - redis
  #     - mongodb
      