#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka-service:8761/eureka/
#      #defaultZone: http://localhost:8761/eureka/
#  instance:
#    preferIpAddress: true
#    #hostname: localhost