// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface ActiveResExistsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.ActiveResExistsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string tip = 2;</code>
   */
  java.lang.String getTip();
  /**
   * <code>string tip = 2;</code>
   */
  com.google.protobuf.ByteString
      getTipBytes();
}
