// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface AnySmestajBelongToHostRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.AnySmestajBelongToHostRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hostId = 1;</code>
   */
  java.lang.String getHostId();
  /**
   * <code>string hostId = 1;</code>
   */
  com.google.protobuf.ByteString
      getHostIdBytes();

  /**
   * <code>repeated string smestajIds = 2;</code>
   */
  java.util.List<java.lang.String>
      getSmestajIdsList();
  /**
   * <code>repeated string smestajIds = 2;</code>
   */
  int getSmestajIdsCount();
  /**
   * <code>repeated string smestajIds = 2;</code>
   */
  java.lang.String getSmestajIds(int index);
  /**
   * <code>repeated string smestajIds = 2;</code>
   */
  com.google.protobuf.ByteString
      getSmestajIdsBytes(int index);
}
