// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface AnySmestajBelongToHostResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.AnySmestajBelongToHostResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool belongs = 1;</code>
   */
  boolean getBelongs();
}
