// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface getListaRezervacijaByUserIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.getListaRezervacijaByUserIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.xml2023.mainapp.RezervacijaDTO listaRezervacija = 1;</code>
   */
  java.util.List<com.xml2023.mainapp.RezervacijaDTO> 
      getListaRezervacijaList();
  /**
   * <code>repeated .com.xml2023.mainapp.RezervacijaDTO listaRezervacija = 1;</code>
   */
  com.xml2023.mainapp.RezervacijaDTO getListaRezervacija(int index);
  /**
   * <code>repeated .com.xml2023.mainapp.RezervacijaDTO listaRezervacija = 1;</code>
   */
  int getListaRezervacijaCount();
  /**
   * <code>repeated .com.xml2023.mainapp.RezervacijaDTO listaRezervacija = 1;</code>
   */
  java.util.List<? extends com.xml2023.mainapp.RezervacijaDTOOrBuilder> 
      getListaRezervacijaOrBuilderList();
  /**
   * <code>repeated .com.xml2023.mainapp.RezervacijaDTO listaRezervacija = 1;</code>
   */
  com.xml2023.mainapp.RezervacijaDTOOrBuilder getListaRezervacijaOrBuilder(
      int index);
}
