// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface NekoOtkazaoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.NekoOtkazaoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string idKorisnika = 1;</code>
   */
  java.lang.String getIdKorisnika();
  /**
   * <code>string idKorisnika = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdKorisnikaBytes();

  /**
   * <code>string idSmestaja = 2;</code>
   */
  java.lang.String getIdSmestaja();
  /**
   * <code>string idSmestaja = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdSmestajaBytes();
}
