// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface OcenaSmestajDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.OcenaSmestajDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>int32 ocena = 2;</code>
   */
  int getOcena();

  /**
   * <code>string idSmestaja = 3;</code>
   */
  java.lang.String getIdSmestaja();
  /**
   * <code>string idSmestaja = 3;</code>
   */
  com.google.protobuf.ByteString
      getIdSmestajaBytes();

  /**
   * <code>string idKorisnika = 4;</code>
   */
  java.lang.String getIdKorisnika();
  /**
   * <code>string idKorisnika = 4;</code>
   */
  com.google.protobuf.ByteString
      getIdKorisnikaBytes();

  /**
   * <code>.google.protobuf.Timestamp datumIVreme = 5;</code>
   */
  boolean hasDatumIVreme();
  /**
   * <code>.google.protobuf.Timestamp datumIVreme = 5;</code>
   */
  com.google.protobuf.Timestamp getDatumIVreme();
  /**
   * <code>.google.protobuf.Timestamp datumIVreme = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDatumIVremeOrBuilder();
}
