// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface SmestajDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.SmestajDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string vlasnik = 2;</code>
   */
  java.lang.String getVlasnik();
  /**
   * <code>string vlasnik = 2;</code>
   */
  com.google.protobuf.ByteString
      getVlasnikBytes();

  /**
   * <code>repeated string pogodnosti = 3;</code>
   */
  java.util.List<java.lang.String>
      getPogodnostiList();
  /**
   * <code>repeated string pogodnosti = 3;</code>
   */
  int getPogodnostiCount();
  /**
   * <code>repeated string pogodnosti = 3;</code>
   */
  java.lang.String getPogodnosti(int index);
  /**
   * <code>repeated string pogodnosti = 3;</code>
   */
  com.google.protobuf.ByteString
      getPogodnostiBytes(int index);

  /**
   * <code>repeated .com.xml2023.mainapp.SlikaDTO slika = 4;</code>
   */
  java.util.List<com.xml2023.mainapp.SlikaDTO> 
      getSlikaList();
  /**
   * <code>repeated .com.xml2023.mainapp.SlikaDTO slika = 4;</code>
   */
  com.xml2023.mainapp.SlikaDTO getSlika(int index);
  /**
   * <code>repeated .com.xml2023.mainapp.SlikaDTO slika = 4;</code>
   */
  int getSlikaCount();
  /**
   * <code>repeated .com.xml2023.mainapp.SlikaDTO slika = 4;</code>
   */
  java.util.List<? extends com.xml2023.mainapp.SlikaDTOOrBuilder> 
      getSlikaOrBuilderList();
  /**
   * <code>repeated .com.xml2023.mainapp.SlikaDTO slika = 4;</code>
   */
  com.xml2023.mainapp.SlikaDTOOrBuilder getSlikaOrBuilder(
      int index);

  /**
   * <code>int32 minGosti = 5;</code>
   */
  int getMinGosti();

  /**
   * <code>int32 maxGost = 6;</code>
   */
  int getMaxGost();

  /**
   * <code>repeated string nedostupni = 7;</code>
   */
  java.util.List<java.lang.String>
      getNedostupniList();
  /**
   * <code>repeated string nedostupni = 7;</code>
   */
  int getNedostupniCount();
  /**
   * <code>repeated string nedostupni = 7;</code>
   */
  java.lang.String getNedostupni(int index);
  /**
   * <code>repeated string nedostupni = 7;</code>
   */
  com.google.protobuf.ByteString
      getNedostupniBytes(int index);
}
