// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public final class Temp {
  private Temp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_KorisnikRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_KorisnikRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_KorisnikResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_KorisnikResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_SmestajExistsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_SmestajExistsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_SmestajExistsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_SmestajExistsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_RezervacijaExistsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_RezervacijaExistsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_RezervacijaExistsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_RezervacijaExistsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_TerminZauzmiRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_TerminZauzmiRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_TerminZauzmiResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_TerminZauzmiResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_TerminOslobodiRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_TerminOslobodiRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_TerminOslobodiResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_TerminOslobodiResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_ActiveReservationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_ActiveReservationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_ActiveReservationsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_ActiveReservationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_ActiveResExistsForSmestajRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_ActiveResExistsForSmestajRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_ActiveResExistsForSmestajResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_ActiveResExistsForSmestajResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_ActiveResExistsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_ActiveResExistsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_ActiveResExistsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_ActiveResExistsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_SmestajIdsForHostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_SmestajIdsForHostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_SmestajIdsForHostResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_SmestajIdsForHostResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_DeleteSmestajsForHostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_DeleteSmestajsForHostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_DeleteSmestajsForHostResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_DeleteSmestajsForHostResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getSmestajByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getSmestajByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getSmestajByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getSmestajByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_SmestajDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_SmestajDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_OcenaSmestajDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_OcenaSmestajDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getOceneBySmestajIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getOceneBySmestajIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getOceneBySmestajIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getOceneBySmestajIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getRezervacijaByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getRezervacijaByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getRezervacijaByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getRezervacijaByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_RezervacijaDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_RezervacijaDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_AdresaDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_AdresaDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_CenovnikDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_CenovnikDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_SlikaDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_SlikaDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_TerminDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_TerminDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_NekoRezervisaoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_NekoRezervisaoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_NekoRezervisaoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_NekoRezervisaoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_NekoOtkazaoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_NekoOtkazaoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_NekoOtkazaoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_NekoOtkazaoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_NekoOcenioSmestajRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_NekoOcenioSmestajRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_NekoOcenioSmestajResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_NekoOcenioSmestajResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_NekoOcenioHostaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_NekoOcenioHostaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_NekoOcenioHostaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_NekoOcenioHostaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_DobioStatusIstaknutogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_DobioStatusIstaknutogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_DobioStatusIstaknutogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_DobioStatusIstaknutogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getHostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getHostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getHostResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getHostResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_HostBasicDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_HostBasicDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_rezOtkazanaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_rezOtkazanaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_rezOtkazanaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_rezOtkazanaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_rezOtkazanaHostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_rezOtkazanaHostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_rezOtkazanaHostResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_rezOtkazanaHostResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_reservationApprovedNotificationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_reservationApprovedNotificationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_reservationApprovedNotificationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_reservationApprovedNotificationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_NovaRezervacijaNotifikacijaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_NovaRezervacijaNotifikacijaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_NovaRezervacijaNotifikacijaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_NovaRezervacijaNotifikacijaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_OtkazanaRezervacijaNotifikacijaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_OtkazanaRezervacijaNotifikacijaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_OtkazanaRezervacijaNotifikacijaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_OtkazanaRezervacijaNotifikacijaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_NovaOcenaHostaNotifikacijaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_NovaOcenaHostaNotifikacijaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_NovaOcenaHostaNotifikacijaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_NovaOcenaHostaNotifikacijaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_NovaOcenaSmestajaNotifikacijaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_NovaOcenaSmestajaNotifikacijaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_NovaOcenaSmestajaNotifikacijaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_NovaOcenaSmestajaNotifikacijaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_StatusIstaknutogNotifikacijaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_StatusIstaknutogNotifikacijaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_StatusIstaknutogNotifikacijaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_StatusIstaknutogNotifikacijaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_AnySmestajBelongToHostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_AnySmestajBelongToHostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_AnySmestajBelongToHostResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_AnySmestajBelongToHostResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntemp.proto\022\023com.xml2023.mainapp\032\037googl" +
      "e/protobuf/timestamp.proto\"\035\n\017KorisnikRe" +
      "quest\022\n\n\002id\030\001 \001(\t\"A\n\020KorisnikResponse\022\027\n" +
      "\017responsemessage\030\001 \001(\t\022\024\n\014responseCode\030\002" +
      " \001(\005\"\"\n\024SmestajExistsRequest\022\n\n\002id\030\001 \001(\t" +
      "\"F\n\025SmestajExistsResponse\022\027\n\017responsemes" +
      "sage\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\"&\n\030Reze" +
      "rvacijaExistsRequest\022\n\n\002id\030\001 \001(\t\"J\n\031Reze" +
      "rvacijaExistsResponse\022\027\n\017responsemessage" +
      "\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\"X\n\023TerminZa" +
      "uzmiRequest\022\021\n\tsmestajId\030\001 \001(\t\022.\n\006termin" +
      "\030\002 \001(\0132\036.com.xml2023.mainapp.TerminDTO\"8" +
      "\n\024TerminZauzmiResponse\022\016\n\006zauzet\030\001 \001(\010\022\020" +
      "\n\010terminId\030\002 \001(\t\"Z\n\025TerminOslobodiReques" +
      "t\022\021\n\tsmestajId\030\001 \001(\t\022.\n\006termin\030\002 \001(\0132\036.c" +
      "om.xml2023.mainapp.TerminDTO\",\n\026TerminOs" +
      "lobodiResponse\022\022\n\noslobodjen\030\001 \001(\010\"\205\001\n\031A" +
      "ctiveReservationsRequest\022\021\n\tsmestajId\030\001 " +
      "\001(\t\022+\n\007pocetak\030\002 \001(\0132\032.google.protobuf.T" +
      "imestamp\022(\n\004kraj\030\003 \001(\0132\032.google.protobuf" +
      ".Timestamp\"[\n\032ActiveReservationsResponse" +
      "\022=\n\020listaRezervacija\030\001 \003(\0132#.com.xml2023" +
      ".mainapp.RezervacijaDTO\"2\n ActiveResExis" +
      "tsForSmestajRequest\022\016\n\006userId\030\001 \001(\t\"3\n!A" +
      "ctiveResExistsForSmestajResponse\022\016\n\006exis" +
      "ts\030\001 \001(\010\"5\n\026ActiveResExistsRequest\022\016\n\006us" +
      "erId\030\001 \001(\t\022\013\n\003tip\030\002 \001(\t\")\n\027ActiveResExis" +
      "tsResponse\022\016\n\006exists\030\001 \001(\005\"*\n\030SmestajIds" +
      "ForHostRequest\022\016\n\006userId\030\001 \001(\t\"/\n\031Smesta" +
      "jIdsForHostResponse\022\022\n\nsmestajIds\030\001 \003(\t\"" +
      ".\n\034DeleteSmestajsForHostRequest\022\016\n\006hostI" +
      "d\030\001 \001(\t\"0\n\035DeleteSmestajsForHostResponse" +
      "\022\017\n\007success\030\001 \001(\005\"-\n\037getListaSmestajaByU" +
      "serIdRequest\022\n\n\002id\030\001 \001(\t\"Z\n getListaSmes" +
      "tajaByUserIdResponse\0226\n\rlistaSmestaja\030\001 " +
      "\003(\0132\037.com.xml2023.mainapp.SmestajDTO\"*\n\025" +
      "getSmestajByIdRequest\022\021\n\tsmestajId\030\001 \001(\t" +
      "\"J\n\026getSmestajByIdResponse\0220\n\007odgovor\030\001 " +
      "\001(\0132\037.com.xml2023.mainapp.SmestajDTO\"\333\002\n" +
      "\nSmestajDTO\022\n\n\002id\030\001 \001(\t\022\017\n\007vlasnik\030\002 \001(\t" +
      "\022\022\n\npogodnosti\030\003 \003(\t\022,\n\005slika\030\004 \003(\0132\035.co" +
      "m.xml2023.mainapp.SlikaDTO\022\020\n\010minGosti\030\005" +
      " \001(\005\022\017\n\007maxGost\030\006 \001(\005\0222\n\nnedostupni\030\007 \003(" +
      "\0132\036.com.xml2023.mainapp.TerminDTO\0222\n\010cen" +
      "ovnik\030\010 \001(\0132 .com.xml2023.mainapp.Cenovn" +
      "ikDTO\022.\n\006adresa\030\t \001(\0132\036.com.xml2023.main" +
      "app.AdresaDTO\0223\n\005ocene\030\n \003(\0132$.com.xml20" +
      "23.mainapp.OcenaSmestajDTO\"\206\001\n\017OcenaSmes" +
      "tajDTO\022\n\n\002id\030\001 \001(\t\022\r\n\005ocena\030\002 \001(\005\022\022\n\nidS" +
      "mestaja\030\003 \001(\t\022\023\n\013idKorisnika\030\004 \001(\t\022/\n\013da" +
      "tumIVreme\030\005 \001(\0132\032.google.protobuf.Timest" +
      "amp\"/\n\032getOceneBySmestajIdRequest\022\021\n\tsme" +
      "stajId\030\001 \001(\t\"R\n\033getOceneBySmestajIdRespo" +
      "nse\0223\n\005ocene\030\001 \003(\0132$.com.xml2023.mainapp" +
      ".OcenaSmestajDTO\"0\n\"getListaRezervacijaB" +
      "yUserIdRequest\022\n\n\002id\030\001 \001(\t\"d\n#getListaRe" +
      "zervacijaByUserIdResponse\022=\n\020listaRezerv" +
      "acija\030\001 \003(\0132#.com.xml2023.mainapp.Rezerv" +
      "acijaDTO\"2\n\031getRezervacijaByIdRequest\022\025\n" +
      "\rrezervacijaId\030\001 \001(\t\"R\n\032getRezervacijaBy" +
      "IdResponse\0224\n\007odgovor\030\001 \001(\0132#.com.xml202" +
      "3.mainapp.RezervacijaDTO\"\300\002\n\016Rezervacija" +
      "DTO\022\n\n\002id\030\001 \001(\t\022\017\n\007smestaj\030\002 \001(\t\022\014\n\004gost" +
      "\030\003 \001(\t\022+\n\007odDatum\030\004 \001(\0132\032.google.protobu" +
      "f.Timestamp\022+\n\007doDatum\030\005 \001(\0132\032.google.pr" +
      "otobuf.Timestamp\022\023\n\013brojGostiju\030\006 \001(\005\022E\n" +
      "\006status\030\007 \001(\01625.com.xml2023.mainapp.Reze" +
      "rvacijaDTO.StatusRezervacije\"M\n\021StatusRe" +
      "zervacije\022\013\n\007PENDING\020\000\022\017\n\013REZERVISANA\020\001\022" +
      "\014\n\010ODBIJENA\020\002\022\014\n\010OTKAZANA\020\003\"A\n\tAdresaDTO" +
      "\022\n\n\002id\030\001 \001(\t\022\016\n\006adresa\030\002 \001(\t\022\013\n\003lat\030\003 \001(" +
      "\001\022\013\n\003lng\030\004 \001(\001\"j\n\013CenovnikDTO\022\022\n\npoSmest" +
      "aju\030\001 \001(\010\022\014\n\004cena\030\002 \001(\003\022\023\n\013cenaPraznik\030\003" +
      " \001(\003\022\022\n\ncenaVikend\030\004 \001(\003\022\020\n\010cenaLeto\030\005 \001" +
      "(\003\"\031\n\010SlikaDTO\022\r\n\005slika\030\001 \001(\t\"b\n\tTerminD" +
      "TO\022+\n\007pocetak\030\001 \001(\0132\032.google.protobuf.Ti" +
      "mestamp\022(\n\004kraj\030\002 \001(\0132\032.google.protobuf." +
      "Timestamp\"@\n\025NekoRezervisaoRequest\022\023\n\013id" +
      "Korisnika\030\001 \001(\t\022\022\n\nidSmestaja\030\002 \001(\t\"(\n\026N" +
      "ekoRezervisaoResponse\022\016\n\006result\030\001 \001(\010\"=\n" +
      "\022NekoOtkazaoRequest\022\023\n\013idKorisnika\030\001 \001(\t" +
      "\022\022\n\nidSmestaja\030\002 \001(\t\"%\n\023NekoOtkazaoRespo" +
      "nse\022\016\n\006result\030\001 \001(\010\"R\n\030NekoOcenioSmestaj" +
      "Request\022\023\n\013idKorisnika\030\001 \001(\t\022\022\n\nidSmesta" +
      "ja\030\002 \001(\t\022\r\n\005ocena\030\003 \001(\005\"+\n\031NekoOcenioSme" +
      "stajResponse\022\016\n\006result\030\001 \001(\010\"<\n\026NekoOcen" +
      "ioHostaRequest\022\023\n\013idKorisnika\030\001 \001(\t\022\r\n\005o" +
      "cena\030\002 \001(\005\")\n\027NekoOcenioHostaResponse\022\016\n" +
      "\006result\030\001 \001(\010\"C\n\034DobioStatusIstaknutogRe" +
      "quest\022\023\n\013idKorisnika\030\001 \001(\t\022\016\n\006status\030\002 \001" +
      "(\010\"/\n\035DobioStatusIstaknutogResponse\022\016\n\006r" +
      "esult\030\001 \001(\010\" \n\016getHostRequest\022\016\n\006hostId\030" +
      "\001 \001(\t\"B\n\017getHostResponse\022/\n\004host\030\001 \001(\0132!" +
      ".com.xml2023.mainapp.HostBasicDTO\"O\n\014Hos" +
      "tBasicDTO\022\021\n\tistaknuti\030\001 \001(\010\022\025\n\rrezAutom" +
      "atski\030\002 \001(\010\022\025\n\rprosecnaOcena\030\003 \001(\003\"%\n\022re" +
      "zOtkazanaRequest\022\017\n\007guestId\030\001 \001(\t\")\n\023rez" +
      "OtkazanaResponse\022\022\n\npenalDodat\030\001 \001(\010\"7\n\026" +
      "rezOtkazanaHostRequest\022\016\n\006hostId\030\001 \001(\t\022\r" +
      "\n\005resId\030\002 \001(\t\"-\n\027rezOtkazanaHostResponse" +
      "\022\022\n\npenalDodat\030\001 \001(\010\"?\n&reservationAppro" +
      "vedNotificationRequest\022\025\n\ridRezervacije\030" +
      "\001 \001(\t\"=\n\'reservationApprovedNotification" +
      "Response\022\022\n\nisporuceno\030\001 \001(\010\"9\n\"NovaReze" +
      "rvacijaNotifikacijaRequest\022\023\n\013idKorisnik" +
      "a\030\001 \001(\t\"5\n#NovaRezervacijaNotifikacijaRe" +
      "sponse\022\016\n\006stanje\030\001 \001(\010\"=\n&OtkazanaRezerv" +
      "acijaNotifikacijaRequest\022\023\n\013idKorisnika\030" +
      "\001 \001(\t\"9\n\'OtkazanaRezervacijaNotifikacija" +
      "Response\022\016\n\006stanje\030\001 \001(\010\"8\n!NovaOcenaHos" +
      "taNotifikacijaRequest\022\023\n\013idKorisnika\030\001 \001" +
      "(\t\"4\n\"NovaOcenaHostaNotifikacijaResponse" +
      "\022\016\n\006stanje\030\001 \001(\010\";\n$NovaOcenaSmestajaNot" +
      "ifikacijaRequest\022\023\n\013idKorisnika\030\001 \001(\t\"7\n" +
      "%NovaOcenaSmestajaNotifikacijaResponse\022\016" +
      "\n\006stanje\030\001 \001(\010\":\n#StatusIstaknutogNotifi" +
      "kacijaRequest\022\023\n\013idKorisnika\030\001 \001(\t\"6\n$St" +
      "atusIstaknutogNotifikacijaResponse\022\016\n\006st" +
      "anje\030\001 \001(\010\"C\n\035AnySmestajBelongToHostRequ" +
      "est\022\016\n\006hostId\030\001 \001(\t\022\022\n\nsmestajIds\030\002 \003(\t\"" +
      "1\n\036AnySmestajBelongToHostResponse\022\017\n\007bel" +
      "ongs\030\001 \001(\0102j\n\017GreetingService\022W\n\010greetin" +
      "g\022$.com.xml2023.mainapp.KorisnikRequest\032" +
      "%.com.xml2023.mainapp.KorisnikResponse2\233" +
      "\010\n\013SmestajGrpc\022_\n\006exists\022).com.xml2023.m" +
      "ainapp.SmestajExistsRequest\032*.com.xml202" +
      "3.mainapp.SmestajExistsResponse\022u\n\024getSm" +
      "estajIdsForHost\022-.com.xml2023.mainapp.Sm" +
      "estajIdsForHostRequest\032..com.xml2023.mai" +
      "napp.SmestajIdsForHostResponse\022~\n\025dekete" +
      "SnestajsForHost\0221.com.xml2023.mainapp.De" +
      "leteSmestajsForHostRequest\0322.com.xml2023" +
      ".mainapp.DeleteSmestajsForHostResponse\022i" +
      "\n\016getSmestajById\022*.com.xml2023.mainapp.g" +
      "etSmestajByIdRequest\032+.com.xml2023.maina" +
      "pp.getSmestajByIdResponse\022\207\001\n\030getListaSm" +
      "estajaByUserId\0224.com.xml2023.mainapp.get" +
      "ListaSmestajaByUserIdRequest\0325.com.xml20" +
      "23.mainapp.getListaSmestajaByUserIdRespo" +
      "nse\022c\n\014zauzmiTermin\022(.com.xml2023.mainap" +
      "p.TerminZauzmiRequest\032).com.xml2023.main" +
      "app.TerminZauzmiResponse\022i\n\016oslobodiTerm" +
      "in\022*.com.xml2023.mainapp.TerminOslobodiR" +
      "equest\032+.com.xml2023.mainapp.TerminOslob" +
      "odiResponse\022x\n\rbelongsToHost\0222.com.xml20" +
      "23.mainapp.AnySmestajBelongToHostRequest" +
      "\0323.com.xml2023.mainapp.AnySmestajBelongT" +
      "oHostResponse\022u\n\020getOceneSmestaja\022/.com." +
      "xml2023.mainapp.getOceneBySmestajIdReque" +
      "st\0320.com.xml2023.mainapp.getOceneBySmest" +
      "ajIdResponse2\375\005\n\017RezervacijaGrpc\022g\n\006exis" +
      "ts\022-.com.xml2023.mainapp.RezervacijaExis" +
      "tsRequest\032..com.xml2023.mainapp.Rezervac" +
      "ijaExistsResponse\022v\n\031reservationsForUser" +
      "Exists\022+.com.xml2023.mainapp.ActiveResEx" +
      "istsRequest\032,.com.xml2023.mainapp.Active" +
      "ResExistsResponse\022u\n\022getRezervacijaById\022" +
      "..com.xml2023.mainapp.getRezervacijaById" +
      "Request\032/.com.xml2023.mainapp.getRezerva" +
      "cijaByIdResponse\022\220\001\n\033getListaRezervacija" +
      "ByUserId\0227.com.xml2023.mainapp.getListaR" +
      "ezervacijaByUserIdRequest\0328.com.xml2023." +
      "mainapp.getListaRezervacijaByUserIdRespo" +
      "nse\022\204\001\n\023resExistsForSmestaj\0225.com.xml202" +
      "3.mainapp.ActiveResExistsForSmestajReque" +
      "st\0326.com.xml2023.mainapp.ActiveResExists" +
      "ForSmestajResponse\022x\n\025getActiveReservati" +
      "ons\022..com.xml2023.mainapp.ActiveReservat" +
      "ionsRequest\032/.com.xml2023.mainapp.Active" +
      "ReservationsResponse2\255\r\n\014KorisnikGrpc\022T\n" +
      "\007getHost\022#.com.xml2023.mainapp.getHostRe" +
      "quest\032$.com.xml2023.mainapp.getHostRespo" +
      "nse\022`\n\013rezOtkazana\022\'.com.xml2023.mainapp" +
      ".rezOtkazanaRequest\032(.com.xml2023.mainap" +
      "p.rezOtkazanaResponse\022l\n\017rezOtkazanaHost" +
      "\022+.com.xml2023.mainapp.rezOtkazanaHostRe" +
      "quest\032,.com.xml2023.mainapp.rezOtkazanaH" +
      "ostResponse\022\213\001\n\016rezObavestenje\022;.com.xml" +
      "2023.mainapp.reservationApprovedNotifica" +
      "tionRequest\032<.com.xml2023.mainapp.reserv" +
      "ationApprovedNotificationResponse\022g\n\014new" +
      "RezNotify\022*.com.xml2023.mainapp.NekoReze" +
      "rvisaoRequest\032+.com.xml2023.mainapp.Neko" +
      "RezervisaoResponse\022b\n\rnewQuitNotify\022\'.co" +
      "m.xml2023.mainapp.NekoOtkazaoRequest\032(.c" +
      "om.xml2023.mainapp.NekoOtkazaoResponse\022o" +
      "\n\016newRankSmestaj\022-.com.xml2023.mainapp.N" +
      "ekoOcenioSmestajRequest\032..com.xml2023.ma" +
      "inapp.NekoOcenioSmestajResponse\022h\n\013newRa" +
      "nkHost\022+.com.xml2023.mainapp.NekoOcenioH" +
      "ostaRequest\032,.com.xml2023.mainapp.NekoOc" +
      "enioHostaResponse\022v\n\ristaknutiHost\0221.com" +
      ".xml2023.mainapp.DobioStatusIstaknutogRe" +
      "quest\0322.com.xml2023.mainapp.DobioStatusI" +
      "staknutogResponse\022\205\001\n\020novaRezNotStatus\0227" +
      ".com.xml2023.mainapp.NovaRezervacijaNoti" +
      "fikacijaRequest\0328.com.xml2023.mainapp.No" +
      "vaRezervacijaNotifikacijaResponse\022\221\001\n\024ot" +
      "kazanaRezNotStatus\022;.com.xml2023.mainapp" +
      ".OtkazanaRezervacijaNotifikacijaRequest\032" +
      "<.com.xml2023.mainapp.OtkazanaRezervacij" +
      "aNotifikacijaResponse\022\212\001\n\027novaOcenaHosta" +
      "NotStatus\0226.com.xml2023.mainapp.NovaOcen" +
      "aHostaNotifikacijaRequest\0327.com.xml2023." +
      "mainapp.NovaOcenaHostaNotifikacijaRespon" +
      "se\022\223\001\n\032novaOcenaSmestajaNotStatus\0229.com." +
      "xml2023.mainapp.NovaOcenaSmestajaNotifik" +
      "acijaRequest\032:.com.xml2023.mainapp.NovaO" +
      "cenaSmestajaNotifikacijaResponse\022\211\001\n\022ist" +
      "aknutiNotStatus\0228.com.xml2023.mainapp.St" +
      "atusIstaknutogNotifikacijaRequest\0329.com." +
      "xml2023.mainapp.StatusIstaknutogNotifika" +
      "cijaResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_com_xml2023_mainapp_KorisnikRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xml2023_mainapp_KorisnikRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_KorisnikRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_xml2023_mainapp_KorisnikResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xml2023_mainapp_KorisnikResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_KorisnikResponse_descriptor,
        new java.lang.String[] { "Responsemessage", "ResponseCode", });
    internal_static_com_xml2023_mainapp_SmestajExistsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_xml2023_mainapp_SmestajExistsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_SmestajExistsRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_xml2023_mainapp_SmestajExistsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_xml2023_mainapp_SmestajExistsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_SmestajExistsResponse_descriptor,
        new java.lang.String[] { "Responsemessage", "ResponseCode", });
    internal_static_com_xml2023_mainapp_RezervacijaExistsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_xml2023_mainapp_RezervacijaExistsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_RezervacijaExistsRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_xml2023_mainapp_RezervacijaExistsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_xml2023_mainapp_RezervacijaExistsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_RezervacijaExistsResponse_descriptor,
        new java.lang.String[] { "Responsemessage", "ResponseCode", });
    internal_static_com_xml2023_mainapp_TerminZauzmiRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_xml2023_mainapp_TerminZauzmiRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_TerminZauzmiRequest_descriptor,
        new java.lang.String[] { "SmestajId", "Termin", });
    internal_static_com_xml2023_mainapp_TerminZauzmiResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_xml2023_mainapp_TerminZauzmiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_TerminZauzmiResponse_descriptor,
        new java.lang.String[] { "Zauzet", "TerminId", });
    internal_static_com_xml2023_mainapp_TerminOslobodiRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_xml2023_mainapp_TerminOslobodiRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_TerminOslobodiRequest_descriptor,
        new java.lang.String[] { "SmestajId", "Termin", });
    internal_static_com_xml2023_mainapp_TerminOslobodiResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_xml2023_mainapp_TerminOslobodiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_TerminOslobodiResponse_descriptor,
        new java.lang.String[] { "Oslobodjen", });
    internal_static_com_xml2023_mainapp_ActiveReservationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_xml2023_mainapp_ActiveReservationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_ActiveReservationsRequest_descriptor,
        new java.lang.String[] { "SmestajId", "Pocetak", "Kraj", });
    internal_static_com_xml2023_mainapp_ActiveReservationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_xml2023_mainapp_ActiveReservationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_ActiveReservationsResponse_descriptor,
        new java.lang.String[] { "ListaRezervacija", });
    internal_static_com_xml2023_mainapp_ActiveResExistsForSmestajRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_xml2023_mainapp_ActiveResExistsForSmestajRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_ActiveResExistsForSmestajRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_com_xml2023_mainapp_ActiveResExistsForSmestajResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_xml2023_mainapp_ActiveResExistsForSmestajResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_ActiveResExistsForSmestajResponse_descriptor,
        new java.lang.String[] { "Exists", });
    internal_static_com_xml2023_mainapp_ActiveResExistsRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_xml2023_mainapp_ActiveResExistsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_ActiveResExistsRequest_descriptor,
        new java.lang.String[] { "UserId", "Tip", });
    internal_static_com_xml2023_mainapp_ActiveResExistsResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_xml2023_mainapp_ActiveResExistsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_ActiveResExistsResponse_descriptor,
        new java.lang.String[] { "Exists", });
    internal_static_com_xml2023_mainapp_SmestajIdsForHostRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_xml2023_mainapp_SmestajIdsForHostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_SmestajIdsForHostRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_com_xml2023_mainapp_SmestajIdsForHostResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_xml2023_mainapp_SmestajIdsForHostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_SmestajIdsForHostResponse_descriptor,
        new java.lang.String[] { "SmestajIds", });
    internal_static_com_xml2023_mainapp_DeleteSmestajsForHostRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_xml2023_mainapp_DeleteSmestajsForHostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_DeleteSmestajsForHostRequest_descriptor,
        new java.lang.String[] { "HostId", });
    internal_static_com_xml2023_mainapp_DeleteSmestajsForHostResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_xml2023_mainapp_DeleteSmestajsForHostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_DeleteSmestajsForHostResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdResponse_descriptor,
        new java.lang.String[] { "ListaSmestaja", });
    internal_static_com_xml2023_mainapp_getSmestajByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_xml2023_mainapp_getSmestajByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getSmestajByIdRequest_descriptor,
        new java.lang.String[] { "SmestajId", });
    internal_static_com_xml2023_mainapp_getSmestajByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_com_xml2023_mainapp_getSmestajByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getSmestajByIdResponse_descriptor,
        new java.lang.String[] { "Odgovor", });
    internal_static_com_xml2023_mainapp_SmestajDTO_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_com_xml2023_mainapp_SmestajDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_SmestajDTO_descriptor,
        new java.lang.String[] { "Id", "Vlasnik", "Pogodnosti", "Slika", "MinGosti", "MaxGost", "Nedostupni", "Cenovnik", "Adresa", "Ocene", });
    internal_static_com_xml2023_mainapp_OcenaSmestajDTO_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_com_xml2023_mainapp_OcenaSmestajDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_OcenaSmestajDTO_descriptor,
        new java.lang.String[] { "Id", "Ocena", "IdSmestaja", "IdKorisnika", "DatumIVreme", });
    internal_static_com_xml2023_mainapp_getOceneBySmestajIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_com_xml2023_mainapp_getOceneBySmestajIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getOceneBySmestajIdRequest_descriptor,
        new java.lang.String[] { "SmestajId", });
    internal_static_com_xml2023_mainapp_getOceneBySmestajIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_com_xml2023_mainapp_getOceneBySmestajIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getOceneBySmestajIdResponse_descriptor,
        new java.lang.String[] { "Ocene", });
    internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdResponse_descriptor,
        new java.lang.String[] { "ListaRezervacija", });
    internal_static_com_xml2023_mainapp_getRezervacijaByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_com_xml2023_mainapp_getRezervacijaByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getRezervacijaByIdRequest_descriptor,
        new java.lang.String[] { "RezervacijaId", });
    internal_static_com_xml2023_mainapp_getRezervacijaByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_com_xml2023_mainapp_getRezervacijaByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getRezervacijaByIdResponse_descriptor,
        new java.lang.String[] { "Odgovor", });
    internal_static_com_xml2023_mainapp_RezervacijaDTO_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_com_xml2023_mainapp_RezervacijaDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_RezervacijaDTO_descriptor,
        new java.lang.String[] { "Id", "Smestaj", "Gost", "OdDatum", "DoDatum", "BrojGostiju", "Status", });
    internal_static_com_xml2023_mainapp_AdresaDTO_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_com_xml2023_mainapp_AdresaDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_AdresaDTO_descriptor,
        new java.lang.String[] { "Id", "Adresa", "Lat", "Lng", });
    internal_static_com_xml2023_mainapp_CenovnikDTO_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_com_xml2023_mainapp_CenovnikDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_CenovnikDTO_descriptor,
        new java.lang.String[] { "PoSmestaju", "Cena", "CenaPraznik", "CenaVikend", "CenaLeto", });
    internal_static_com_xml2023_mainapp_SlikaDTO_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_com_xml2023_mainapp_SlikaDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_SlikaDTO_descriptor,
        new java.lang.String[] { "Slika", });
    internal_static_com_xml2023_mainapp_TerminDTO_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_com_xml2023_mainapp_TerminDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_TerminDTO_descriptor,
        new java.lang.String[] { "Pocetak", "Kraj", });
    internal_static_com_xml2023_mainapp_NekoRezervisaoRequest_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_com_xml2023_mainapp_NekoRezervisaoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_NekoRezervisaoRequest_descriptor,
        new java.lang.String[] { "IdKorisnika", "IdSmestaja", });
    internal_static_com_xml2023_mainapp_NekoRezervisaoResponse_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_com_xml2023_mainapp_NekoRezervisaoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_NekoRezervisaoResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_com_xml2023_mainapp_NekoOtkazaoRequest_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_com_xml2023_mainapp_NekoOtkazaoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_NekoOtkazaoRequest_descriptor,
        new java.lang.String[] { "IdKorisnika", "IdSmestaja", });
    internal_static_com_xml2023_mainapp_NekoOtkazaoResponse_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_com_xml2023_mainapp_NekoOtkazaoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_NekoOtkazaoResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_com_xml2023_mainapp_NekoOcenioSmestajRequest_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_com_xml2023_mainapp_NekoOcenioSmestajRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_NekoOcenioSmestajRequest_descriptor,
        new java.lang.String[] { "IdKorisnika", "IdSmestaja", "Ocena", });
    internal_static_com_xml2023_mainapp_NekoOcenioSmestajResponse_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_com_xml2023_mainapp_NekoOcenioSmestajResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_NekoOcenioSmestajResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_com_xml2023_mainapp_NekoOcenioHostaRequest_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_com_xml2023_mainapp_NekoOcenioHostaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_NekoOcenioHostaRequest_descriptor,
        new java.lang.String[] { "IdKorisnika", "Ocena", });
    internal_static_com_xml2023_mainapp_NekoOcenioHostaResponse_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_com_xml2023_mainapp_NekoOcenioHostaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_NekoOcenioHostaResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_com_xml2023_mainapp_DobioStatusIstaknutogRequest_descriptor =
      getDescriptor().getMessageTypes().get(45);
    internal_static_com_xml2023_mainapp_DobioStatusIstaknutogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_DobioStatusIstaknutogRequest_descriptor,
        new java.lang.String[] { "IdKorisnika", "Status", });
    internal_static_com_xml2023_mainapp_DobioStatusIstaknutogResponse_descriptor =
      getDescriptor().getMessageTypes().get(46);
    internal_static_com_xml2023_mainapp_DobioStatusIstaknutogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_DobioStatusIstaknutogResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_com_xml2023_mainapp_getHostRequest_descriptor =
      getDescriptor().getMessageTypes().get(47);
    internal_static_com_xml2023_mainapp_getHostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getHostRequest_descriptor,
        new java.lang.String[] { "HostId", });
    internal_static_com_xml2023_mainapp_getHostResponse_descriptor =
      getDescriptor().getMessageTypes().get(48);
    internal_static_com_xml2023_mainapp_getHostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getHostResponse_descriptor,
        new java.lang.String[] { "Host", });
    internal_static_com_xml2023_mainapp_HostBasicDTO_descriptor =
      getDescriptor().getMessageTypes().get(49);
    internal_static_com_xml2023_mainapp_HostBasicDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_HostBasicDTO_descriptor,
        new java.lang.String[] { "Istaknuti", "RezAutomatski", "ProsecnaOcena", });
    internal_static_com_xml2023_mainapp_rezOtkazanaRequest_descriptor =
      getDescriptor().getMessageTypes().get(50);
    internal_static_com_xml2023_mainapp_rezOtkazanaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_rezOtkazanaRequest_descriptor,
        new java.lang.String[] { "GuestId", });
    internal_static_com_xml2023_mainapp_rezOtkazanaResponse_descriptor =
      getDescriptor().getMessageTypes().get(51);
    internal_static_com_xml2023_mainapp_rezOtkazanaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_rezOtkazanaResponse_descriptor,
        new java.lang.String[] { "PenalDodat", });
    internal_static_com_xml2023_mainapp_rezOtkazanaHostRequest_descriptor =
      getDescriptor().getMessageTypes().get(52);
    internal_static_com_xml2023_mainapp_rezOtkazanaHostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_rezOtkazanaHostRequest_descriptor,
        new java.lang.String[] { "HostId", "ResId", });
    internal_static_com_xml2023_mainapp_rezOtkazanaHostResponse_descriptor =
      getDescriptor().getMessageTypes().get(53);
    internal_static_com_xml2023_mainapp_rezOtkazanaHostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_rezOtkazanaHostResponse_descriptor,
        new java.lang.String[] { "PenalDodat", });
    internal_static_com_xml2023_mainapp_reservationApprovedNotificationRequest_descriptor =
      getDescriptor().getMessageTypes().get(54);
    internal_static_com_xml2023_mainapp_reservationApprovedNotificationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_reservationApprovedNotificationRequest_descriptor,
        new java.lang.String[] { "IdRezervacije", });
    internal_static_com_xml2023_mainapp_reservationApprovedNotificationResponse_descriptor =
      getDescriptor().getMessageTypes().get(55);
    internal_static_com_xml2023_mainapp_reservationApprovedNotificationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_reservationApprovedNotificationResponse_descriptor,
        new java.lang.String[] { "Isporuceno", });
    internal_static_com_xml2023_mainapp_NovaRezervacijaNotifikacijaRequest_descriptor =
      getDescriptor().getMessageTypes().get(56);
    internal_static_com_xml2023_mainapp_NovaRezervacijaNotifikacijaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_NovaRezervacijaNotifikacijaRequest_descriptor,
        new java.lang.String[] { "IdKorisnika", });
    internal_static_com_xml2023_mainapp_NovaRezervacijaNotifikacijaResponse_descriptor =
      getDescriptor().getMessageTypes().get(57);
    internal_static_com_xml2023_mainapp_NovaRezervacijaNotifikacijaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_NovaRezervacijaNotifikacijaResponse_descriptor,
        new java.lang.String[] { "Stanje", });
    internal_static_com_xml2023_mainapp_OtkazanaRezervacijaNotifikacijaRequest_descriptor =
      getDescriptor().getMessageTypes().get(58);
    internal_static_com_xml2023_mainapp_OtkazanaRezervacijaNotifikacijaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_OtkazanaRezervacijaNotifikacijaRequest_descriptor,
        new java.lang.String[] { "IdKorisnika", });
    internal_static_com_xml2023_mainapp_OtkazanaRezervacijaNotifikacijaResponse_descriptor =
      getDescriptor().getMessageTypes().get(59);
    internal_static_com_xml2023_mainapp_OtkazanaRezervacijaNotifikacijaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_OtkazanaRezervacijaNotifikacijaResponse_descriptor,
        new java.lang.String[] { "Stanje", });
    internal_static_com_xml2023_mainapp_NovaOcenaHostaNotifikacijaRequest_descriptor =
      getDescriptor().getMessageTypes().get(60);
    internal_static_com_xml2023_mainapp_NovaOcenaHostaNotifikacijaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_NovaOcenaHostaNotifikacijaRequest_descriptor,
        new java.lang.String[] { "IdKorisnika", });
    internal_static_com_xml2023_mainapp_NovaOcenaHostaNotifikacijaResponse_descriptor =
      getDescriptor().getMessageTypes().get(61);
    internal_static_com_xml2023_mainapp_NovaOcenaHostaNotifikacijaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_NovaOcenaHostaNotifikacijaResponse_descriptor,
        new java.lang.String[] { "Stanje", });
    internal_static_com_xml2023_mainapp_NovaOcenaSmestajaNotifikacijaRequest_descriptor =
      getDescriptor().getMessageTypes().get(62);
    internal_static_com_xml2023_mainapp_NovaOcenaSmestajaNotifikacijaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_NovaOcenaSmestajaNotifikacijaRequest_descriptor,
        new java.lang.String[] { "IdKorisnika", });
    internal_static_com_xml2023_mainapp_NovaOcenaSmestajaNotifikacijaResponse_descriptor =
      getDescriptor().getMessageTypes().get(63);
    internal_static_com_xml2023_mainapp_NovaOcenaSmestajaNotifikacijaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_NovaOcenaSmestajaNotifikacijaResponse_descriptor,
        new java.lang.String[] { "Stanje", });
    internal_static_com_xml2023_mainapp_StatusIstaknutogNotifikacijaRequest_descriptor =
      getDescriptor().getMessageTypes().get(64);
    internal_static_com_xml2023_mainapp_StatusIstaknutogNotifikacijaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_StatusIstaknutogNotifikacijaRequest_descriptor,
        new java.lang.String[] { "IdKorisnika", });
    internal_static_com_xml2023_mainapp_StatusIstaknutogNotifikacijaResponse_descriptor =
      getDescriptor().getMessageTypes().get(65);
    internal_static_com_xml2023_mainapp_StatusIstaknutogNotifikacijaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_StatusIstaknutogNotifikacijaResponse_descriptor,
        new java.lang.String[] { "Stanje", });
    internal_static_com_xml2023_mainapp_AnySmestajBelongToHostRequest_descriptor =
      getDescriptor().getMessageTypes().get(66);
    internal_static_com_xml2023_mainapp_AnySmestajBelongToHostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_AnySmestajBelongToHostRequest_descriptor,
        new java.lang.String[] { "HostId", "SmestajIds", });
    internal_static_com_xml2023_mainapp_AnySmestajBelongToHostResponse_descriptor =
      getDescriptor().getMessageTypes().get(67);
    internal_static_com_xml2023_mainapp_AnySmestajBelongToHostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_AnySmestajBelongToHostResponse_descriptor,
        new java.lang.String[] { "Belongs", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
