// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface TerminZauzmiRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.TerminZauzmiRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string smestajId = 1;</code>
   */
  java.lang.String getSmestajId();
  /**
   * <code>string smestajId = 1;</code>
   */
  com.google.protobuf.ByteString
      getSmestajIdBytes();

  /**
   * <code>.com.xml2023.mainapp.TerminDTO termin = 2;</code>
   */
  boolean hasTermin();
  /**
   * <code>.com.xml2023.mainapp.TerminDTO termin = 2;</code>
   */
  com.xml2023.mainapp.TerminDTO getTermin();
  /**
   * <code>.com.xml2023.mainapp.TerminDTO termin = 2;</code>
   */
  com.xml2023.mainapp.TerminDTOOrBuilder getTerminOrBuilder();
}
