// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

/**
 * Protobuf type {@code com.xml2023.mainapp.TerminDTO}
 */
public  final class TerminDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.xml2023.mainapp.TerminDTO)
    TerminDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TerminDTO.newBuilder() to construct.
  private TerminDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TerminDTO() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TerminDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (pocetak_ != null) {
              subBuilder = pocetak_.toBuilder();
            }
            pocetak_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pocetak_);
              pocetak_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (kraj_ != null) {
              subBuilder = kraj_.toBuilder();
            }
            kraj_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(kraj_);
              kraj_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xml2023.mainapp.Temp.internal_static_com_xml2023_mainapp_TerminDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xml2023.mainapp.Temp.internal_static_com_xml2023_mainapp_TerminDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xml2023.mainapp.TerminDTO.class, com.xml2023.mainapp.TerminDTO.Builder.class);
  }

  public static final int POCETAK_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp pocetak_;
  /**
   * <code>.google.protobuf.Timestamp pocetak = 1;</code>
   */
  public boolean hasPocetak() {
    return pocetak_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp pocetak = 1;</code>
   */
  public com.google.protobuf.Timestamp getPocetak() {
    return pocetak_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : pocetak_;
  }
  /**
   * <code>.google.protobuf.Timestamp pocetak = 1;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getPocetakOrBuilder() {
    return getPocetak();
  }

  public static final int KRAJ_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp kraj_;
  /**
   * <code>.google.protobuf.Timestamp kraj = 2;</code>
   */
  public boolean hasKraj() {
    return kraj_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp kraj = 2;</code>
   */
  public com.google.protobuf.Timestamp getKraj() {
    return kraj_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : kraj_;
  }
  /**
   * <code>.google.protobuf.Timestamp kraj = 2;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getKrajOrBuilder() {
    return getKraj();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pocetak_ != null) {
      output.writeMessage(1, getPocetak());
    }
    if (kraj_ != null) {
      output.writeMessage(2, getKraj());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pocetak_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPocetak());
    }
    if (kraj_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getKraj());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xml2023.mainapp.TerminDTO)) {
      return super.equals(obj);
    }
    com.xml2023.mainapp.TerminDTO other = (com.xml2023.mainapp.TerminDTO) obj;

    boolean result = true;
    result = result && (hasPocetak() == other.hasPocetak());
    if (hasPocetak()) {
      result = result && getPocetak()
          .equals(other.getPocetak());
    }
    result = result && (hasKraj() == other.hasKraj());
    if (hasKraj()) {
      result = result && getKraj()
          .equals(other.getKraj());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPocetak()) {
      hash = (37 * hash) + POCETAK_FIELD_NUMBER;
      hash = (53 * hash) + getPocetak().hashCode();
    }
    if (hasKraj()) {
      hash = (37 * hash) + KRAJ_FIELD_NUMBER;
      hash = (53 * hash) + getKraj().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xml2023.mainapp.TerminDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xml2023.mainapp.TerminDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xml2023.mainapp.TerminDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xml2023.mainapp.TerminDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xml2023.mainapp.TerminDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xml2023.mainapp.TerminDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xml2023.mainapp.TerminDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xml2023.mainapp.TerminDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xml2023.mainapp.TerminDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xml2023.mainapp.TerminDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xml2023.mainapp.TerminDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xml2023.mainapp.TerminDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xml2023.mainapp.TerminDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.xml2023.mainapp.TerminDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.xml2023.mainapp.TerminDTO)
      com.xml2023.mainapp.TerminDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xml2023.mainapp.Temp.internal_static_com_xml2023_mainapp_TerminDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xml2023.mainapp.Temp.internal_static_com_xml2023_mainapp_TerminDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xml2023.mainapp.TerminDTO.class, com.xml2023.mainapp.TerminDTO.Builder.class);
    }

    // Construct using com.xml2023.mainapp.TerminDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (pocetakBuilder_ == null) {
        pocetak_ = null;
      } else {
        pocetak_ = null;
        pocetakBuilder_ = null;
      }
      if (krajBuilder_ == null) {
        kraj_ = null;
      } else {
        kraj_ = null;
        krajBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xml2023.mainapp.Temp.internal_static_com_xml2023_mainapp_TerminDTO_descriptor;
    }

    @java.lang.Override
    public com.xml2023.mainapp.TerminDTO getDefaultInstanceForType() {
      return com.xml2023.mainapp.TerminDTO.getDefaultInstance();
    }

    @java.lang.Override
    public com.xml2023.mainapp.TerminDTO build() {
      com.xml2023.mainapp.TerminDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xml2023.mainapp.TerminDTO buildPartial() {
      com.xml2023.mainapp.TerminDTO result = new com.xml2023.mainapp.TerminDTO(this);
      if (pocetakBuilder_ == null) {
        result.pocetak_ = pocetak_;
      } else {
        result.pocetak_ = pocetakBuilder_.build();
      }
      if (krajBuilder_ == null) {
        result.kraj_ = kraj_;
      } else {
        result.kraj_ = krajBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xml2023.mainapp.TerminDTO) {
        return mergeFrom((com.xml2023.mainapp.TerminDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xml2023.mainapp.TerminDTO other) {
      if (other == com.xml2023.mainapp.TerminDTO.getDefaultInstance()) return this;
      if (other.hasPocetak()) {
        mergePocetak(other.getPocetak());
      }
      if (other.hasKraj()) {
        mergeKraj(other.getKraj());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xml2023.mainapp.TerminDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xml2023.mainapp.TerminDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Timestamp pocetak_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> pocetakBuilder_;
    /**
     * <code>.google.protobuf.Timestamp pocetak = 1;</code>
     */
    public boolean hasPocetak() {
      return pocetakBuilder_ != null || pocetak_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp pocetak = 1;</code>
     */
    public com.google.protobuf.Timestamp getPocetak() {
      if (pocetakBuilder_ == null) {
        return pocetak_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : pocetak_;
      } else {
        return pocetakBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp pocetak = 1;</code>
     */
    public Builder setPocetak(com.google.protobuf.Timestamp value) {
      if (pocetakBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pocetak_ = value;
        onChanged();
      } else {
        pocetakBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp pocetak = 1;</code>
     */
    public Builder setPocetak(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (pocetakBuilder_ == null) {
        pocetak_ = builderForValue.build();
        onChanged();
      } else {
        pocetakBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp pocetak = 1;</code>
     */
    public Builder mergePocetak(com.google.protobuf.Timestamp value) {
      if (pocetakBuilder_ == null) {
        if (pocetak_ != null) {
          pocetak_ =
            com.google.protobuf.Timestamp.newBuilder(pocetak_).mergeFrom(value).buildPartial();
        } else {
          pocetak_ = value;
        }
        onChanged();
      } else {
        pocetakBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp pocetak = 1;</code>
     */
    public Builder clearPocetak() {
      if (pocetakBuilder_ == null) {
        pocetak_ = null;
        onChanged();
      } else {
        pocetak_ = null;
        pocetakBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp pocetak = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getPocetakBuilder() {
      
      onChanged();
      return getPocetakFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp pocetak = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getPocetakOrBuilder() {
      if (pocetakBuilder_ != null) {
        return pocetakBuilder_.getMessageOrBuilder();
      } else {
        return pocetak_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : pocetak_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp pocetak = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getPocetakFieldBuilder() {
      if (pocetakBuilder_ == null) {
        pocetakBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getPocetak(),
                getParentForChildren(),
                isClean());
        pocetak_ = null;
      }
      return pocetakBuilder_;
    }

    private com.google.protobuf.Timestamp kraj_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> krajBuilder_;
    /**
     * <code>.google.protobuf.Timestamp kraj = 2;</code>
     */
    public boolean hasKraj() {
      return krajBuilder_ != null || kraj_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp kraj = 2;</code>
     */
    public com.google.protobuf.Timestamp getKraj() {
      if (krajBuilder_ == null) {
        return kraj_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : kraj_;
      } else {
        return krajBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp kraj = 2;</code>
     */
    public Builder setKraj(com.google.protobuf.Timestamp value) {
      if (krajBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kraj_ = value;
        onChanged();
      } else {
        krajBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp kraj = 2;</code>
     */
    public Builder setKraj(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (krajBuilder_ == null) {
        kraj_ = builderForValue.build();
        onChanged();
      } else {
        krajBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp kraj = 2;</code>
     */
    public Builder mergeKraj(com.google.protobuf.Timestamp value) {
      if (krajBuilder_ == null) {
        if (kraj_ != null) {
          kraj_ =
            com.google.protobuf.Timestamp.newBuilder(kraj_).mergeFrom(value).buildPartial();
        } else {
          kraj_ = value;
        }
        onChanged();
      } else {
        krajBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp kraj = 2;</code>
     */
    public Builder clearKraj() {
      if (krajBuilder_ == null) {
        kraj_ = null;
        onChanged();
      } else {
        kraj_ = null;
        krajBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp kraj = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getKrajBuilder() {
      
      onChanged();
      return getKrajFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp kraj = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getKrajOrBuilder() {
      if (krajBuilder_ != null) {
        return krajBuilder_.getMessageOrBuilder();
      } else {
        return kraj_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : kraj_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp kraj = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getKrajFieldBuilder() {
      if (krajBuilder_ == null) {
        krajBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getKraj(),
                getParentForChildren(),
                isClean());
        kraj_ = null;
      }
      return krajBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.xml2023.mainapp.TerminDTO)
  }

  // @@protoc_insertion_point(class_scope:com.xml2023.mainapp.TerminDTO)
  private static final com.xml2023.mainapp.TerminDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xml2023.mainapp.TerminDTO();
  }

  public static com.xml2023.mainapp.TerminDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TerminDTO>
      PARSER = new com.google.protobuf.AbstractParser<TerminDTO>() {
    @java.lang.Override
    public TerminDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TerminDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TerminDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TerminDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xml2023.mainapp.TerminDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

