// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface CenovnikDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.CenovnikDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool poSmestaju = 1;</code>
   */
  boolean getPoSmestaju();

  /**
   * <code>int64 cena = 2;</code>
   */
  long getCena();

  /**
   * <code>int64 cenaPraznik = 3;</code>
   */
  long getCenaPraznik();

  /**
   * <code>int64 cenaVikend = 4;</code>
   */
  long getCenaVikend();

  /**
   * <code>int64 cenaLeto = 5;</code>
   */
  long getCenaLeto();
}
