// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface getHostRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.getHostRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hostId = 1;</code>
   */
  java.lang.String getHostId();
  /**
   * <code>string hostId = 1;</code>
   */
  com.google.protobuf.ByteString
      getHostIdBytes();
}
