// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface getRezervacijaByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.getRezervacijaByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.xml2023.mainapp.RezervacijaDTO odgovor = 1;</code>
   */
  boolean hasOdgovor();
  /**
   * <code>.com.xml2023.mainapp.RezervacijaDTO odgovor = 1;</code>
   */
  com.xml2023.mainapp.RezervacijaDTO getOdgovor();
  /**
   * <code>.com.xml2023.mainapp.RezervacijaDTO odgovor = 1;</code>
   */
  com.xml2023.mainapp.RezervacijaDTOOrBuilder getOdgovorOrBuilder();
}
