// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface getSmestajByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.getSmestajByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.xml2023.mainapp.SmestajDTO odgovor = 1;</code>
   */
  boolean hasOdgovor();
  /**
   * <code>.com.xml2023.mainapp.SmestajDTO odgovor = 1;</code>
   */
  com.xml2023.mainapp.SmestajDTO getOdgovor();
  /**
   * <code>.com.xml2023.mainapp.SmestajDTO odgovor = 1;</code>
   */
  com.xml2023.mainapp.SmestajDTOOrBuilder getOdgovorOrBuilder();
}
