// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface HostBasicDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.HostBasicDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool istaknuti = 1;</code>
   */
  boolean getIstaknuti();

  /**
   * <code>bool rezAutomatski = 2;</code>
   */
  boolean getRezAutomatski();

  /**
   * <code>int64 prosecnaOcena = 3;</code>
   */
  long getProsecnaOcena();
}
