// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface rezOtkazanaRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.rezOtkazanaRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string guestId = 1;</code>
   */
  java.lang.String getGuestId();
  /**
   * <code>string guestId = 1;</code>
   */
  com.google.protobuf.ByteString
      getGuestIdBytes();
}
