// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public final class Temp {
  private Temp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_KorisnikRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_KorisnikRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_KorisnikResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_KorisnikResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_SmestajExistsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_SmestajExistsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_SmestajExistsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_SmestajExistsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_RezervacijaExistsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_RezervacijaExistsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_RezervacijaExistsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_RezervacijaExistsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_ActiveResExistsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_ActiveResExistsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_ActiveResExistsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_ActiveResExistsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_SmestajIdsForHostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_SmestajIdsForHostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_SmestajIdsForHostResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_SmestajIdsForHostResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_DeleteSmestajsForHostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_DeleteSmestajsForHostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_DeleteSmestajsForHostResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_DeleteSmestajsForHostResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getSmestajByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getSmestajByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getSmestajByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getSmestajByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_SmestajDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_SmestajDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getRezervacijaByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getRezervacijaByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_getRezervacijaByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_getRezervacijaByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_RezervacijaDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_RezervacijaDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_AdresaDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_AdresaDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_CenovnikDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_CenovnikDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_SlikaDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_SlikaDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xml2023_mainapp_TerminDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xml2023_mainapp_TerminDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntemp.proto\022\023com.xml2023.mainapp\032\037googl" +
      "e/protobuf/timestamp.proto\"\035\n\017KorisnikRe" +
      "quest\022\n\n\002id\030\001 \001(\t\"A\n\020KorisnikResponse\022\027\n" +
      "\017responsemessage\030\001 \001(\t\022\024\n\014responseCode\030\002" +
      " \001(\005\"\"\n\024SmestajExistsRequest\022\n\n\002id\030\001 \001(\t" +
      "\"F\n\025SmestajExistsResponse\022\027\n\017responsemes" +
      "sage\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\"&\n\030Reze" +
      "rvacijaExistsRequest\022\n\n\002id\030\001 \001(\t\"J\n\031Reze" +
      "rvacijaExistsResponse\022\027\n\017responsemessage" +
      "\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\"5\n\026ActiveRe" +
      "sExistsRequest\022\016\n\006userId\030\001 \001(\t\022\013\n\003tip\030\002 " +
      "\001(\t\")\n\027ActiveResExistsResponse\022\016\n\006exists" +
      "\030\001 \001(\005\"*\n\030SmestajIdsForHostRequest\022\016\n\006us" +
      "erId\030\001 \001(\t\"/\n\031SmestajIdsForHostResponse\022" +
      "\022\n\nsmestajIds\030\001 \003(\t\".\n\034DeleteSmestajsFor" +
      "HostRequest\022\016\n\006hostId\030\001 \001(\t\"0\n\035DeleteSme" +
      "stajsForHostResponse\022\017\n\007success\030\001 \001(\005\"-\n" +
      "\037getListaSmestajaByUserIdRequest\022\n\n\002id\030\001" +
      " \001(\t\"Z\n getListaSmestajaByUserIdResponse" +
      "\0226\n\rlistaSmestaja\030\001 \003(\0132\037.com.xml2023.ma" +
      "inapp.SmestajDTO\"*\n\025getSmestajByIdReques" +
      "t\022\021\n\tsmestajId\030\001 \001(\t\"J\n\026getSmestajByIdRe" +
      "sponse\0220\n\007odgovor\030\001 \001(\0132\037.com.xml2023.ma" +
      "inapp.SmestajDTO\"\326\001\n\nSmestajDTO\022\n\n\002id\030\001 " +
      "\001(\t\022\017\n\007vlasnik\030\002 \001(\t\022\022\n\npogodnosti\030\003 \003(\t" +
      "\022,\n\005slika\030\004 \003(\0132\035.com.xml2023.mainapp.Sl" +
      "ikaDTO\022\020\n\010minGosti\030\005 \001(\005\022\017\n\007maxGost\030\006 \001(" +
      "\005\022\022\n\nnedostupni\030\007 \003(\t\0222\n\010cenovnik\030\010 \001(\0132" +
      " .com.xml2023.mainapp.CenovnikDTO\"0\n\"get" +
      "ListaRezervacijaByUserIdRequest\022\n\n\002id\030\001 " +
      "\001(\t\"d\n#getListaRezervacijaByUserIdRespon" +
      "se\022=\n\020listaRezervacija\030\001 \003(\0132#.com.xml20" +
      "23.mainapp.RezervacijaDTO\"2\n\031getRezervac" +
      "ijaByIdRequest\022\025\n\rrezervacijaId\030\001 \001(\t\"R\n" +
      "\032getRezervacijaByIdResponse\0224\n\007odgovor\030\001" +
      " \001(\0132#.com.xml2023.mainapp.RezervacijaDT" +
      "O\"\300\002\n\016RezervacijaDTO\022\n\n\002id\030\001 \001(\t\022\017\n\007smes" +
      "taj\030\002 \001(\t\022\014\n\004gost\030\003 \001(\t\022+\n\007odDatum\030\004 \001(\013" +
      "2\032.google.protobuf.Timestamp\022+\n\007doDatum\030" +
      "\005 \001(\0132\032.google.protobuf.Timestamp\022\023\n\013bro" +
      "jGostiju\030\006 \001(\005\022E\n\006status\030\007 \001(\01625.com.xml" +
      "2023.mainapp.RezervacijaDTO.StatusRezerv" +
      "acije\"M\n\021StatusRezervacije\022\013\n\007PENDING\020\000\022" +
      "\017\n\013REZERVISANA\020\001\022\014\n\010ODBIJENA\020\002\022\014\n\010OTKAZA" +
      "NA\020\003\"A\n\tAdresaDTO\022\n\n\002id\030\001 \001(\t\022\016\n\006adresa\030" +
      "\002 \001(\t\022\013\n\003lat\030\003 \001(\001\022\013\n\003lng\030\004 \001(\001\"j\n\013Cenov" +
      "nikDTO\022\022\n\npoSmestaju\030\001 \001(\010\022\014\n\004cena\030\002 \001(\003" +
      "\022\023\n\013cenaPraznik\030\003 \001(\003\022\022\n\ncenaVikend\030\004 \001(" +
      "\003\022\020\n\010cenaLeto\030\005 \001(\003\"\031\n\010SlikaDTO\022\r\n\005slika" +
      "\030\001 \001(\t\"b\n\tTerminDTO\022+\n\007pocetak\030\001 \001(\0132\032.g" +
      "oogle.protobuf.Timestamp\022(\n\004kraj\030\002 \001(\0132\032" +
      ".google.protobuf.Timestamp2j\n\017GreetingSe" +
      "rvice\022W\n\010greeting\022$.com.xml2023.mainapp." +
      "KorisnikRequest\032%.com.xml2023.mainapp.Ko" +
      "risnikResponse2\332\004\n\013SmestajGrpc\022_\n\006exists" +
      "\022).com.xml2023.mainapp.SmestajExistsRequ" +
      "est\032*.com.xml2023.mainapp.SmestajExistsR" +
      "esponse\022u\n\024getSmestajIdsForHost\022-.com.xm" +
      "l2023.mainapp.SmestajIdsForHostRequest\032." +
      ".com.xml2023.mainapp.SmestajIdsForHostRe" +
      "sponse\022~\n\025deketeSnestajsForHost\0221.com.xm" +
      "l2023.mainapp.DeleteSmestajsForHostReque" +
      "st\0322.com.xml2023.mainapp.DeleteSmestajsF" +
      "orHostResponse\022i\n\016getSmestajById\022*.com.x" +
      "ml2023.mainapp.getSmestajByIdRequest\032+.c" +
      "om.xml2023.mainapp.getSmestajByIdRespons" +
      "e\022\207\001\n\030getListaSmestajaByUserId\0224.com.xml" +
      "2023.mainapp.getListaSmestajaByUserIdReq" +
      "uest\0325.com.xml2023.mainapp.getListaSmest" +
      "ajaByUserIdResponse2\374\003\n\017RezervacijaGrpc\022" +
      "g\n\006exists\022-.com.xml2023.mainapp.Rezervac" +
      "ijaExistsRequest\032..com.xml2023.mainapp.R" +
      "ezervacijaExistsResponse\022v\n\031reservations" +
      "ForUserExists\022+.com.xml2023.mainapp.Acti" +
      "veResExistsRequest\032,.com.xml2023.mainapp" +
      ".ActiveResExistsResponse\022u\n\022getRezervaci" +
      "jaById\022..com.xml2023.mainapp.getRezervac" +
      "ijaByIdRequest\032/.com.xml2023.mainapp.get" +
      "RezervacijaByIdResponse\022\220\001\n\033getListaReze" +
      "rvacijaByUserId\0227.com.xml2023.mainapp.ge" +
      "tListaRezervacijaByUserIdRequest\0328.com.x" +
      "ml2023.mainapp.getListaRezervacijaByUser" +
      "IdResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_com_xml2023_mainapp_KorisnikRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xml2023_mainapp_KorisnikRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_KorisnikRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_xml2023_mainapp_KorisnikResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xml2023_mainapp_KorisnikResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_KorisnikResponse_descriptor,
        new java.lang.String[] { "Responsemessage", "ResponseCode", });
    internal_static_com_xml2023_mainapp_SmestajExistsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_xml2023_mainapp_SmestajExistsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_SmestajExistsRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_xml2023_mainapp_SmestajExistsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_xml2023_mainapp_SmestajExistsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_SmestajExistsResponse_descriptor,
        new java.lang.String[] { "Responsemessage", "ResponseCode", });
    internal_static_com_xml2023_mainapp_RezervacijaExistsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_xml2023_mainapp_RezervacijaExistsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_RezervacijaExistsRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_xml2023_mainapp_RezervacijaExistsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_xml2023_mainapp_RezervacijaExistsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_RezervacijaExistsResponse_descriptor,
        new java.lang.String[] { "Responsemessage", "ResponseCode", });
    internal_static_com_xml2023_mainapp_ActiveResExistsRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_xml2023_mainapp_ActiveResExistsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_ActiveResExistsRequest_descriptor,
        new java.lang.String[] { "UserId", "Tip", });
    internal_static_com_xml2023_mainapp_ActiveResExistsResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_xml2023_mainapp_ActiveResExistsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_ActiveResExistsResponse_descriptor,
        new java.lang.String[] { "Exists", });
    internal_static_com_xml2023_mainapp_SmestajIdsForHostRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_xml2023_mainapp_SmestajIdsForHostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_SmestajIdsForHostRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_com_xml2023_mainapp_SmestajIdsForHostResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_xml2023_mainapp_SmestajIdsForHostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_SmestajIdsForHostResponse_descriptor,
        new java.lang.String[] { "SmestajIds", });
    internal_static_com_xml2023_mainapp_DeleteSmestajsForHostRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_xml2023_mainapp_DeleteSmestajsForHostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_DeleteSmestajsForHostRequest_descriptor,
        new java.lang.String[] { "HostId", });
    internal_static_com_xml2023_mainapp_DeleteSmestajsForHostResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_xml2023_mainapp_DeleteSmestajsForHostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_DeleteSmestajsForHostResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdResponse_descriptor,
        new java.lang.String[] { "ListaSmestaja", });
    internal_static_com_xml2023_mainapp_getSmestajByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_xml2023_mainapp_getSmestajByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getSmestajByIdRequest_descriptor,
        new java.lang.String[] { "SmestajId", });
    internal_static_com_xml2023_mainapp_getSmestajByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_xml2023_mainapp_getSmestajByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getSmestajByIdResponse_descriptor,
        new java.lang.String[] { "Odgovor", });
    internal_static_com_xml2023_mainapp_SmestajDTO_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_xml2023_mainapp_SmestajDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_SmestajDTO_descriptor,
        new java.lang.String[] { "Id", "Vlasnik", "Pogodnosti", "Slika", "MinGosti", "MaxGost", "Nedostupni", "Cenovnik", });
    internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getListaRezervacijaByUserIdResponse_descriptor,
        new java.lang.String[] { "ListaRezervacija", });
    internal_static_com_xml2023_mainapp_getRezervacijaByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_xml2023_mainapp_getRezervacijaByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getRezervacijaByIdRequest_descriptor,
        new java.lang.String[] { "RezervacijaId", });
    internal_static_com_xml2023_mainapp_getRezervacijaByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_xml2023_mainapp_getRezervacijaByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_getRezervacijaByIdResponse_descriptor,
        new java.lang.String[] { "Odgovor", });
    internal_static_com_xml2023_mainapp_RezervacijaDTO_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_xml2023_mainapp_RezervacijaDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_RezervacijaDTO_descriptor,
        new java.lang.String[] { "Id", "Smestaj", "Gost", "OdDatum", "DoDatum", "BrojGostiju", "Status", });
    internal_static_com_xml2023_mainapp_AdresaDTO_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_xml2023_mainapp_AdresaDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_AdresaDTO_descriptor,
        new java.lang.String[] { "Id", "Adresa", "Lat", "Lng", });
    internal_static_com_xml2023_mainapp_CenovnikDTO_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_com_xml2023_mainapp_CenovnikDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_CenovnikDTO_descriptor,
        new java.lang.String[] { "PoSmestaju", "Cena", "CenaPraznik", "CenaVikend", "CenaLeto", });
    internal_static_com_xml2023_mainapp_SlikaDTO_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_com_xml2023_mainapp_SlikaDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_SlikaDTO_descriptor,
        new java.lang.String[] { "Slika", });
    internal_static_com_xml2023_mainapp_TerminDTO_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_com_xml2023_mainapp_TerminDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xml2023_mainapp_TerminDTO_descriptor,
        new java.lang.String[] { "Pocetak", "Kraj", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
