// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface TerminDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.TerminDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp pocetak = 1;</code>
   */
  boolean hasPocetak();
  /**
   * <code>.google.protobuf.Timestamp pocetak = 1;</code>
   */
  com.google.protobuf.Timestamp getPocetak();
  /**
   * <code>.google.protobuf.Timestamp pocetak = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getPocetakOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp kraj = 2;</code>
   */
  boolean hasKraj();
  /**
   * <code>.google.protobuf.Timestamp kraj = 2;</code>
   */
  com.google.protobuf.Timestamp getKraj();
  /**
   * <code>.google.protobuf.Timestamp kraj = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getKrajOrBuilder();
}
