// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface AdresaDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.AdresaDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string adresa = 2;</code>
   */
  java.lang.String getAdresa();
  /**
   * <code>string adresa = 2;</code>
   */
  com.google.protobuf.ByteString
      getAdresaBytes();

  /**
   * <code>double lat = 3;</code>
   */
  double getLat();

  /**
   * <code>double lng = 4;</code>
   */
  double getLng();
}
