// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

/**
 * Protobuf type {@code com.xml2023.mainapp.AnySmestajBelongToHostRequest}
 */
public  final class AnySmestajBelongToHostRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.xml2023.mainapp.AnySmestajBelongToHostRequest)
    AnySmestajBelongToHostRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AnySmestajBelongToHostRequest.newBuilder() to construct.
  private AnySmestajBelongToHostRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AnySmestajBelongToHostRequest() {
    hostId_ = "";
    smestajIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AnySmestajBelongToHostRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            hostId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              smestajIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            smestajIds_.add(s);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        smestajIds_ = smestajIds_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xml2023.mainapp.Temp.internal_static_com_xml2023_mainapp_AnySmestajBelongToHostRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xml2023.mainapp.Temp.internal_static_com_xml2023_mainapp_AnySmestajBelongToHostRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xml2023.mainapp.AnySmestajBelongToHostRequest.class, com.xml2023.mainapp.AnySmestajBelongToHostRequest.Builder.class);
  }

  private int bitField0_;
  public static final int HOSTID_FIELD_NUMBER = 1;
  private volatile java.lang.Object hostId_;
  /**
   * <code>string hostId = 1;</code>
   */
  public java.lang.String getHostId() {
    java.lang.Object ref = hostId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hostId_ = s;
      return s;
    }
  }
  /**
   * <code>string hostId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getHostIdBytes() {
    java.lang.Object ref = hostId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hostId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SMESTAJIDS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList smestajIds_;
  /**
   * <code>repeated string smestajIds = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getSmestajIdsList() {
    return smestajIds_;
  }
  /**
   * <code>repeated string smestajIds = 2;</code>
   */
  public int getSmestajIdsCount() {
    return smestajIds_.size();
  }
  /**
   * <code>repeated string smestajIds = 2;</code>
   */
  public java.lang.String getSmestajIds(int index) {
    return smestajIds_.get(index);
  }
  /**
   * <code>repeated string smestajIds = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSmestajIdsBytes(int index) {
    return smestajIds_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getHostIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hostId_);
    }
    for (int i = 0; i < smestajIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, smestajIds_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getHostIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hostId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < smestajIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(smestajIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSmestajIdsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xml2023.mainapp.AnySmestajBelongToHostRequest)) {
      return super.equals(obj);
    }
    com.xml2023.mainapp.AnySmestajBelongToHostRequest other = (com.xml2023.mainapp.AnySmestajBelongToHostRequest) obj;

    boolean result = true;
    result = result && getHostId()
        .equals(other.getHostId());
    result = result && getSmestajIdsList()
        .equals(other.getSmestajIdsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HOSTID_FIELD_NUMBER;
    hash = (53 * hash) + getHostId().hashCode();
    if (getSmestajIdsCount() > 0) {
      hash = (37 * hash) + SMESTAJIDS_FIELD_NUMBER;
      hash = (53 * hash) + getSmestajIdsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xml2023.mainapp.AnySmestajBelongToHostRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xml2023.mainapp.AnySmestajBelongToHostRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xml2023.mainapp.AnySmestajBelongToHostRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xml2023.mainapp.AnySmestajBelongToHostRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xml2023.mainapp.AnySmestajBelongToHostRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xml2023.mainapp.AnySmestajBelongToHostRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xml2023.mainapp.AnySmestajBelongToHostRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xml2023.mainapp.AnySmestajBelongToHostRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xml2023.mainapp.AnySmestajBelongToHostRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xml2023.mainapp.AnySmestajBelongToHostRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xml2023.mainapp.AnySmestajBelongToHostRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xml2023.mainapp.AnySmestajBelongToHostRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xml2023.mainapp.AnySmestajBelongToHostRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.xml2023.mainapp.AnySmestajBelongToHostRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.xml2023.mainapp.AnySmestajBelongToHostRequest)
      com.xml2023.mainapp.AnySmestajBelongToHostRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xml2023.mainapp.Temp.internal_static_com_xml2023_mainapp_AnySmestajBelongToHostRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xml2023.mainapp.Temp.internal_static_com_xml2023_mainapp_AnySmestajBelongToHostRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xml2023.mainapp.AnySmestajBelongToHostRequest.class, com.xml2023.mainapp.AnySmestajBelongToHostRequest.Builder.class);
    }

    // Construct using com.xml2023.mainapp.AnySmestajBelongToHostRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      hostId_ = "";

      smestajIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xml2023.mainapp.Temp.internal_static_com_xml2023_mainapp_AnySmestajBelongToHostRequest_descriptor;
    }

    @java.lang.Override
    public com.xml2023.mainapp.AnySmestajBelongToHostRequest getDefaultInstanceForType() {
      return com.xml2023.mainapp.AnySmestajBelongToHostRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.xml2023.mainapp.AnySmestajBelongToHostRequest build() {
      com.xml2023.mainapp.AnySmestajBelongToHostRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xml2023.mainapp.AnySmestajBelongToHostRequest buildPartial() {
      com.xml2023.mainapp.AnySmestajBelongToHostRequest result = new com.xml2023.mainapp.AnySmestajBelongToHostRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.hostId_ = hostId_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        smestajIds_ = smestajIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.smestajIds_ = smestajIds_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xml2023.mainapp.AnySmestajBelongToHostRequest) {
        return mergeFrom((com.xml2023.mainapp.AnySmestajBelongToHostRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xml2023.mainapp.AnySmestajBelongToHostRequest other) {
      if (other == com.xml2023.mainapp.AnySmestajBelongToHostRequest.getDefaultInstance()) return this;
      if (!other.getHostId().isEmpty()) {
        hostId_ = other.hostId_;
        onChanged();
      }
      if (!other.smestajIds_.isEmpty()) {
        if (smestajIds_.isEmpty()) {
          smestajIds_ = other.smestajIds_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureSmestajIdsIsMutable();
          smestajIds_.addAll(other.smestajIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xml2023.mainapp.AnySmestajBelongToHostRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xml2023.mainapp.AnySmestajBelongToHostRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object hostId_ = "";
    /**
     * <code>string hostId = 1;</code>
     */
    public java.lang.String getHostId() {
      java.lang.Object ref = hostId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hostId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHostIdBytes() {
      java.lang.Object ref = hostId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hostId = 1;</code>
     */
    public Builder setHostId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hostId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string hostId = 1;</code>
     */
    public Builder clearHostId() {
      
      hostId_ = getDefaultInstance().getHostId();
      onChanged();
      return this;
    }
    /**
     * <code>string hostId = 1;</code>
     */
    public Builder setHostIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hostId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList smestajIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureSmestajIdsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        smestajIds_ = new com.google.protobuf.LazyStringArrayList(smestajIds_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string smestajIds = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSmestajIdsList() {
      return smestajIds_.getUnmodifiableView();
    }
    /**
     * <code>repeated string smestajIds = 2;</code>
     */
    public int getSmestajIdsCount() {
      return smestajIds_.size();
    }
    /**
     * <code>repeated string smestajIds = 2;</code>
     */
    public java.lang.String getSmestajIds(int index) {
      return smestajIds_.get(index);
    }
    /**
     * <code>repeated string smestajIds = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSmestajIdsBytes(int index) {
      return smestajIds_.getByteString(index);
    }
    /**
     * <code>repeated string smestajIds = 2;</code>
     */
    public Builder setSmestajIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSmestajIdsIsMutable();
      smestajIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string smestajIds = 2;</code>
     */
    public Builder addSmestajIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSmestajIdsIsMutable();
      smestajIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string smestajIds = 2;</code>
     */
    public Builder addAllSmestajIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureSmestajIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, smestajIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string smestajIds = 2;</code>
     */
    public Builder clearSmestajIds() {
      smestajIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string smestajIds = 2;</code>
     */
    public Builder addSmestajIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureSmestajIdsIsMutable();
      smestajIds_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.xml2023.mainapp.AnySmestajBelongToHostRequest)
  }

  // @@protoc_insertion_point(class_scope:com.xml2023.mainapp.AnySmestajBelongToHostRequest)
  private static final com.xml2023.mainapp.AnySmestajBelongToHostRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xml2023.mainapp.AnySmestajBelongToHostRequest();
  }

  public static com.xml2023.mainapp.AnySmestajBelongToHostRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnySmestajBelongToHostRequest>
      PARSER = new com.google.protobuf.AbstractParser<AnySmestajBelongToHostRequest>() {
    @java.lang.Override
    public AnySmestajBelongToHostRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AnySmestajBelongToHostRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AnySmestajBelongToHostRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnySmestajBelongToHostRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xml2023.mainapp.AnySmestajBelongToHostRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

