// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

/**
 * Protobuf type {@code com.xml2023.mainapp.getListaSmestajaByUserIdResponse}
 */
public  final class getListaSmestajaByUserIdResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.xml2023.mainapp.getListaSmestajaByUserIdResponse)
    getListaSmestajaByUserIdResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use getListaSmestajaByUserIdResponse.newBuilder() to construct.
  private getListaSmestajaByUserIdResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private getListaSmestajaByUserIdResponse() {
    listaSmestaja_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private getListaSmestajaByUserIdResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              listaSmestaja_ = new java.util.ArrayList<com.xml2023.mainapp.SmestajDTO>();
              mutable_bitField0_ |= 0x00000001;
            }
            listaSmestaja_.add(
                input.readMessage(com.xml2023.mainapp.SmestajDTO.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        listaSmestaja_ = java.util.Collections.unmodifiableList(listaSmestaja_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xml2023.mainapp.Temp.internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xml2023.mainapp.Temp.internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xml2023.mainapp.getListaSmestajaByUserIdResponse.class, com.xml2023.mainapp.getListaSmestajaByUserIdResponse.Builder.class);
  }

  public static final int LISTASMESTAJA_FIELD_NUMBER = 1;
  private java.util.List<com.xml2023.mainapp.SmestajDTO> listaSmestaja_;
  /**
   * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
   */
  public java.util.List<com.xml2023.mainapp.SmestajDTO> getListaSmestajaList() {
    return listaSmestaja_;
  }
  /**
   * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
   */
  public java.util.List<? extends com.xml2023.mainapp.SmestajDTOOrBuilder> 
      getListaSmestajaOrBuilderList() {
    return listaSmestaja_;
  }
  /**
   * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
   */
  public int getListaSmestajaCount() {
    return listaSmestaja_.size();
  }
  /**
   * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
   */
  public com.xml2023.mainapp.SmestajDTO getListaSmestaja(int index) {
    return listaSmestaja_.get(index);
  }
  /**
   * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
   */
  public com.xml2023.mainapp.SmestajDTOOrBuilder getListaSmestajaOrBuilder(
      int index) {
    return listaSmestaja_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < listaSmestaja_.size(); i++) {
      output.writeMessage(1, listaSmestaja_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < listaSmestaja_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, listaSmestaja_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xml2023.mainapp.getListaSmestajaByUserIdResponse)) {
      return super.equals(obj);
    }
    com.xml2023.mainapp.getListaSmestajaByUserIdResponse other = (com.xml2023.mainapp.getListaSmestajaByUserIdResponse) obj;

    boolean result = true;
    result = result && getListaSmestajaList()
        .equals(other.getListaSmestajaList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getListaSmestajaCount() > 0) {
      hash = (37 * hash) + LISTASMESTAJA_FIELD_NUMBER;
      hash = (53 * hash) + getListaSmestajaList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xml2023.mainapp.getListaSmestajaByUserIdResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xml2023.mainapp.getListaSmestajaByUserIdResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xml2023.mainapp.getListaSmestajaByUserIdResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xml2023.mainapp.getListaSmestajaByUserIdResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xml2023.mainapp.getListaSmestajaByUserIdResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xml2023.mainapp.getListaSmestajaByUserIdResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xml2023.mainapp.getListaSmestajaByUserIdResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xml2023.mainapp.getListaSmestajaByUserIdResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xml2023.mainapp.getListaSmestajaByUserIdResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xml2023.mainapp.getListaSmestajaByUserIdResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xml2023.mainapp.getListaSmestajaByUserIdResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xml2023.mainapp.getListaSmestajaByUserIdResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xml2023.mainapp.getListaSmestajaByUserIdResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.xml2023.mainapp.getListaSmestajaByUserIdResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.xml2023.mainapp.getListaSmestajaByUserIdResponse)
      com.xml2023.mainapp.getListaSmestajaByUserIdResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xml2023.mainapp.Temp.internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xml2023.mainapp.Temp.internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xml2023.mainapp.getListaSmestajaByUserIdResponse.class, com.xml2023.mainapp.getListaSmestajaByUserIdResponse.Builder.class);
    }

    // Construct using com.xml2023.mainapp.getListaSmestajaByUserIdResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getListaSmestajaFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (listaSmestajaBuilder_ == null) {
        listaSmestaja_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        listaSmestajaBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xml2023.mainapp.Temp.internal_static_com_xml2023_mainapp_getListaSmestajaByUserIdResponse_descriptor;
    }

    @java.lang.Override
    public com.xml2023.mainapp.getListaSmestajaByUserIdResponse getDefaultInstanceForType() {
      return com.xml2023.mainapp.getListaSmestajaByUserIdResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.xml2023.mainapp.getListaSmestajaByUserIdResponse build() {
      com.xml2023.mainapp.getListaSmestajaByUserIdResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xml2023.mainapp.getListaSmestajaByUserIdResponse buildPartial() {
      com.xml2023.mainapp.getListaSmestajaByUserIdResponse result = new com.xml2023.mainapp.getListaSmestajaByUserIdResponse(this);
      int from_bitField0_ = bitField0_;
      if (listaSmestajaBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          listaSmestaja_ = java.util.Collections.unmodifiableList(listaSmestaja_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.listaSmestaja_ = listaSmestaja_;
      } else {
        result.listaSmestaja_ = listaSmestajaBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xml2023.mainapp.getListaSmestajaByUserIdResponse) {
        return mergeFrom((com.xml2023.mainapp.getListaSmestajaByUserIdResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xml2023.mainapp.getListaSmestajaByUserIdResponse other) {
      if (other == com.xml2023.mainapp.getListaSmestajaByUserIdResponse.getDefaultInstance()) return this;
      if (listaSmestajaBuilder_ == null) {
        if (!other.listaSmestaja_.isEmpty()) {
          if (listaSmestaja_.isEmpty()) {
            listaSmestaja_ = other.listaSmestaja_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureListaSmestajaIsMutable();
            listaSmestaja_.addAll(other.listaSmestaja_);
          }
          onChanged();
        }
      } else {
        if (!other.listaSmestaja_.isEmpty()) {
          if (listaSmestajaBuilder_.isEmpty()) {
            listaSmestajaBuilder_.dispose();
            listaSmestajaBuilder_ = null;
            listaSmestaja_ = other.listaSmestaja_;
            bitField0_ = (bitField0_ & ~0x00000001);
            listaSmestajaBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getListaSmestajaFieldBuilder() : null;
          } else {
            listaSmestajaBuilder_.addAllMessages(other.listaSmestaja_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xml2023.mainapp.getListaSmestajaByUserIdResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xml2023.mainapp.getListaSmestajaByUserIdResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.xml2023.mainapp.SmestajDTO> listaSmestaja_ =
      java.util.Collections.emptyList();
    private void ensureListaSmestajaIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        listaSmestaja_ = new java.util.ArrayList<com.xml2023.mainapp.SmestajDTO>(listaSmestaja_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xml2023.mainapp.SmestajDTO, com.xml2023.mainapp.SmestajDTO.Builder, com.xml2023.mainapp.SmestajDTOOrBuilder> listaSmestajaBuilder_;

    /**
     * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
     */
    public java.util.List<com.xml2023.mainapp.SmestajDTO> getListaSmestajaList() {
      if (listaSmestajaBuilder_ == null) {
        return java.util.Collections.unmodifiableList(listaSmestaja_);
      } else {
        return listaSmestajaBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
     */
    public int getListaSmestajaCount() {
      if (listaSmestajaBuilder_ == null) {
        return listaSmestaja_.size();
      } else {
        return listaSmestajaBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
     */
    public com.xml2023.mainapp.SmestajDTO getListaSmestaja(int index) {
      if (listaSmestajaBuilder_ == null) {
        return listaSmestaja_.get(index);
      } else {
        return listaSmestajaBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
     */
    public Builder setListaSmestaja(
        int index, com.xml2023.mainapp.SmestajDTO value) {
      if (listaSmestajaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListaSmestajaIsMutable();
        listaSmestaja_.set(index, value);
        onChanged();
      } else {
        listaSmestajaBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
     */
    public Builder setListaSmestaja(
        int index, com.xml2023.mainapp.SmestajDTO.Builder builderForValue) {
      if (listaSmestajaBuilder_ == null) {
        ensureListaSmestajaIsMutable();
        listaSmestaja_.set(index, builderForValue.build());
        onChanged();
      } else {
        listaSmestajaBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
     */
    public Builder addListaSmestaja(com.xml2023.mainapp.SmestajDTO value) {
      if (listaSmestajaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListaSmestajaIsMutable();
        listaSmestaja_.add(value);
        onChanged();
      } else {
        listaSmestajaBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
     */
    public Builder addListaSmestaja(
        int index, com.xml2023.mainapp.SmestajDTO value) {
      if (listaSmestajaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListaSmestajaIsMutable();
        listaSmestaja_.add(index, value);
        onChanged();
      } else {
        listaSmestajaBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
     */
    public Builder addListaSmestaja(
        com.xml2023.mainapp.SmestajDTO.Builder builderForValue) {
      if (listaSmestajaBuilder_ == null) {
        ensureListaSmestajaIsMutable();
        listaSmestaja_.add(builderForValue.build());
        onChanged();
      } else {
        listaSmestajaBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
     */
    public Builder addListaSmestaja(
        int index, com.xml2023.mainapp.SmestajDTO.Builder builderForValue) {
      if (listaSmestajaBuilder_ == null) {
        ensureListaSmestajaIsMutable();
        listaSmestaja_.add(index, builderForValue.build());
        onChanged();
      } else {
        listaSmestajaBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
     */
    public Builder addAllListaSmestaja(
        java.lang.Iterable<? extends com.xml2023.mainapp.SmestajDTO> values) {
      if (listaSmestajaBuilder_ == null) {
        ensureListaSmestajaIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, listaSmestaja_);
        onChanged();
      } else {
        listaSmestajaBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
     */
    public Builder clearListaSmestaja() {
      if (listaSmestajaBuilder_ == null) {
        listaSmestaja_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        listaSmestajaBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
     */
    public Builder removeListaSmestaja(int index) {
      if (listaSmestajaBuilder_ == null) {
        ensureListaSmestajaIsMutable();
        listaSmestaja_.remove(index);
        onChanged();
      } else {
        listaSmestajaBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
     */
    public com.xml2023.mainapp.SmestajDTO.Builder getListaSmestajaBuilder(
        int index) {
      return getListaSmestajaFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
     */
    public com.xml2023.mainapp.SmestajDTOOrBuilder getListaSmestajaOrBuilder(
        int index) {
      if (listaSmestajaBuilder_ == null) {
        return listaSmestaja_.get(index);  } else {
        return listaSmestajaBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
     */
    public java.util.List<? extends com.xml2023.mainapp.SmestajDTOOrBuilder> 
         getListaSmestajaOrBuilderList() {
      if (listaSmestajaBuilder_ != null) {
        return listaSmestajaBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(listaSmestaja_);
      }
    }
    /**
     * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
     */
    public com.xml2023.mainapp.SmestajDTO.Builder addListaSmestajaBuilder() {
      return getListaSmestajaFieldBuilder().addBuilder(
          com.xml2023.mainapp.SmestajDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
     */
    public com.xml2023.mainapp.SmestajDTO.Builder addListaSmestajaBuilder(
        int index) {
      return getListaSmestajaFieldBuilder().addBuilder(
          index, com.xml2023.mainapp.SmestajDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
     */
    public java.util.List<com.xml2023.mainapp.SmestajDTO.Builder> 
         getListaSmestajaBuilderList() {
      return getListaSmestajaFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xml2023.mainapp.SmestajDTO, com.xml2023.mainapp.SmestajDTO.Builder, com.xml2023.mainapp.SmestajDTOOrBuilder> 
        getListaSmestajaFieldBuilder() {
      if (listaSmestajaBuilder_ == null) {
        listaSmestajaBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.xml2023.mainapp.SmestajDTO, com.xml2023.mainapp.SmestajDTO.Builder, com.xml2023.mainapp.SmestajDTOOrBuilder>(
                listaSmestaja_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        listaSmestaja_ = null;
      }
      return listaSmestajaBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.xml2023.mainapp.getListaSmestajaByUserIdResponse)
  }

  // @@protoc_insertion_point(class_scope:com.xml2023.mainapp.getListaSmestajaByUserIdResponse)
  private static final com.xml2023.mainapp.getListaSmestajaByUserIdResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xml2023.mainapp.getListaSmestajaByUserIdResponse();
  }

  public static com.xml2023.mainapp.getListaSmestajaByUserIdResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<getListaSmestajaByUserIdResponse>
      PARSER = new com.google.protobuf.AbstractParser<getListaSmestajaByUserIdResponse>() {
    @java.lang.Override
    public getListaSmestajaByUserIdResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new getListaSmestajaByUserIdResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<getListaSmestajaByUserIdResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<getListaSmestajaByUserIdResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xml2023.mainapp.getListaSmestajaByUserIdResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

