// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface getListaSmestajaByUserIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.getListaSmestajaByUserIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
   */
  java.util.List<com.xml2023.mainapp.SmestajDTO> 
      getListaSmestajaList();
  /**
   * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
   */
  com.xml2023.mainapp.SmestajDTO getListaSmestaja(int index);
  /**
   * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
   */
  int getListaSmestajaCount();
  /**
   * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
   */
  java.util.List<? extends com.xml2023.mainapp.SmestajDTOOrBuilder> 
      getListaSmestajaOrBuilderList();
  /**
   * <code>repeated .com.xml2023.mainapp.SmestajDTO listaSmestaja = 1;</code>
   */
  com.xml2023.mainapp.SmestajDTOOrBuilder getListaSmestajaOrBuilder(
      int index);
}
