// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface getOceneBySmestajIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.getOceneBySmestajIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.xml2023.mainapp.OcenaSmestajDTO ocene = 1;</code>
   */
  java.util.List<com.xml2023.mainapp.OcenaSmestajDTO> 
      getOceneList();
  /**
   * <code>repeated .com.xml2023.mainapp.OcenaSmestajDTO ocene = 1;</code>
   */
  com.xml2023.mainapp.OcenaSmestajDTO getOcene(int index);
  /**
   * <code>repeated .com.xml2023.mainapp.OcenaSmestajDTO ocene = 1;</code>
   */
  int getOceneCount();
  /**
   * <code>repeated .com.xml2023.mainapp.OcenaSmestajDTO ocene = 1;</code>
   */
  java.util.List<? extends com.xml2023.mainapp.OcenaSmestajDTOOrBuilder> 
      getOceneOrBuilderList();
  /**
   * <code>repeated .com.xml2023.mainapp.OcenaSmestajDTO ocene = 1;</code>
   */
  com.xml2023.mainapp.OcenaSmestajDTOOrBuilder getOceneOrBuilder(
      int index);
}
