// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface OtkazanaRezervacijaNotifikacijaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.OtkazanaRezervacijaNotifikacijaResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool stanje = 1;</code>
   */
  boolean getStanje();
}
