// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface reservationApprovedNotificationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.reservationApprovedNotificationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isporuceno = 1;</code>
   */
  boolean getIsporuceno();
}
