// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface RezervacijaDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.RezervacijaDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string smestaj = 2;</code>
   */
  java.lang.String getSmestaj();
  /**
   * <code>string smestaj = 2;</code>
   */
  com.google.protobuf.ByteString
      getSmestajBytes();

  /**
   * <code>string gost = 3;</code>
   */
  java.lang.String getGost();
  /**
   * <code>string gost = 3;</code>
   */
  com.google.protobuf.ByteString
      getGostBytes();

  /**
   * <code>.google.protobuf.Timestamp odDatum = 4;</code>
   */
  boolean hasOdDatum();
  /**
   * <code>.google.protobuf.Timestamp odDatum = 4;</code>
   */
  com.google.protobuf.Timestamp getOdDatum();
  /**
   * <code>.google.protobuf.Timestamp odDatum = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getOdDatumOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp doDatum = 5;</code>
   */
  boolean hasDoDatum();
  /**
   * <code>.google.protobuf.Timestamp doDatum = 5;</code>
   */
  com.google.protobuf.Timestamp getDoDatum();
  /**
   * <code>.google.protobuf.Timestamp doDatum = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDoDatumOrBuilder();

  /**
   * <code>int32 brojGostiju = 6;</code>
   */
  int getBrojGostiju();

  /**
   * <code>.com.xml2023.mainapp.RezervacijaDTO.StatusRezervacije status = 7;</code>
   */
  int getStatusValue();
  /**
   * <code>.com.xml2023.mainapp.RezervacijaDTO.StatusRezervacije status = 7;</code>
   */
  com.xml2023.mainapp.RezervacijaDTO.StatusRezervacije getStatus();
}
