// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface rezOtkazanaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.rezOtkazanaResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool penalDodat = 1;</code>
   */
  boolean getPenalDodat();
}
