// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.xml2023.mainapp;

public interface SmestajIdsForHostResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xml2023.mainapp.SmestajIdsForHostResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string smestajIds = 1;</code>
   */
  java.util.List<java.lang.String>
      getSmestajIdsList();
  /**
   * <code>repeated string smestajIds = 1;</code>
   */
  int getSmestajIdsCount();
  /**
   * <code>repeated string smestajIds = 1;</code>
   */
  java.lang.String getSmestajIds(int index);
  /**
   * <code>repeated string smestajIds = 1;</code>
   */
  com.google.protobuf.ByteString
      getSmestajIdsBytes(int index);
}
